/**
 * Whether a page's lead repeats its purpose line: the cases are the openings
 * a mirrored page and a hub really have, and the near-misses that must keep
 * the purpose line.
 */
import { describe, expect, it } from 'vitest';

import { leadRepeats, leadText, plainWords } from './intro';

const MIRRORED = [
  '<!-- GENERATED by tools/src/site/gen-site-docs.ts from docs/x.md. Do not edit this file. -->',
  '',
  '',
  "Stops calling a service that's **already** failing — so callers fail fast.",
  'And a second line of the same paragraph.',
  '',
  '## What it is',
].join('\n');

describe('leadText', () => {
  it('passes the stamp and blank lines, and reads the first paragraph whole', () => {
    expect(leadText(MIRRORED)).toBe(
      "stops calling a service that's already failing — so callers fail fast. and a second line of the same paragraph.",
    );
  });

  it('passes a hub’s comment and import, and finds no lead where the body opens with a heading, a list or markup', () => {
    expect(
      leadText("{/* GENERATED */}\n\nimport X from './x';\n\nKeeping answers close\n\n<X />"),
    ).toBe('keeping answers close');
    expect(leadText('## What it is\n\nText.')).toBe('');
    expect(leadText('- one\n- two')).toBe('');
    expect(leadText('<SiteMap />')).toBe('');
    expect(leadText(undefined)).toBe('');
  });
});

describe('plainWords', () => {
  it('reads links, emphasis, code and an id suffix as the words a reader sees', () => {
    expect(plainWords('A [Circuit  Breaker](../x.html) is `open` _now_ {#description-p-1}')).toBe(
      'a circuit breaker is open now',
    );
  });
});

describe('leadRepeats', () => {
  it('is true when the lead opens with the purpose line, a closing stop ignored', () => {
    expect(leadRepeats("Stops calling a service that's already failing", MIRRORED)).toBe(true);
    expect(leadRepeats("Stops calling a service that's already failing.", MIRRORED)).toBe(true);
  });

  it('is false when the lead says something else, only part of it, or nothing', () => {
    expect(leadRepeats('Isolates resources so one failure cannot sink all', MIRRORED)).toBe(false);
    expect(leadRepeats('Stops calling a service that is already failing', MIRRORED)).toBe(false);
    expect(leadRepeats("Stops calling a service that's already failing", '## Heading first')).toBe(
      false,
    );
    expect(leadRepeats('', MIRRORED)).toBe(false);
  });
});
