#!/usr/bin/env bash
# .claude/hooks/after-write.sh — the PostToolUse advisory that names what an
# edit owes while the edit is fresh.
#
# The assertions that matter are not only "does it advise". They are that it
# says nothing on the ordinary edit (an advisory that fires on every write is
# noise, and noise is ignored), that each note names a command rather than a
# concept, that a malformed payload leaves it silent with exit 0 — it runs
# after every edit in the repo — and that it never touches the tree.
set -uo pipefail
# shellcheck source=tests/lib.sh disable=SC1091
. "$(dirname "$0")/../lib.sh"

HOOK="$KB_REPO_ROOT/.claude/hooks/after-write.sh"
GATE=tools/src/gates/check-claude-md.ts

# Run the hook with an Edit payload naming <path>, relative to $PROJECT.
advise() { # <path>
  run_hook "$HOOK" "$(edit_payload "$PROJECT/$1")"
}

assert_advises() { # <path> <needle> <label>
  advise "$1"
  assert_hook_advises "$3" "$2"
}

assert_quiet() { # <path> <label>
  advise "$1"
  assert_hook_silent "$2"
}

words() { # <n> <file> — a file of exactly n words
  awk -v n="$1" 'BEGIN { for (i = 0; i < n; i++) printf "word " }' > "$2"
}

echo "== the hook is installable at all =="
assert_file "$HOOK" "the hook exists"
assert_executable "$HOOK" "the hook is executable"

make_sandbox
# The layer gate is where the hook reads its budgets; a copy, so a case below
# can change a constant without touching the real gate.
mkdir -p "$PROJECT/tools/src/gates" "$PROJECT/docs/reference" "$PROJECT/docs/data"
cp "$KB_REPO_ROOT/$GATE" "$PROJECT/$GATE"
jq -n '{gates:[{id:"gates-fresh", wired:"node_modules/.bin/tsx tools/src/gen/gen-gates.ts --check", fix:"make gates"}]}' \
  > "$PROJECT/docs/data/gates.json"

echo "== hooks-O1 =="
printf -- '---\ntitle: Check gates\n---\n\n<!-- GENERATED by tools/src/gen/gen-gates.ts from docs/data/gates.json. Do not edit this file. -->\n\n# Check gates\n' \
  > "$PROJECT/docs/reference/gates.md"
advise "docs/reference/gates.md"
assert_hook_advises "hooks-O1: a stamped reference page" "tools/src/gen/gen-gates.ts"
assert_contains "$OUTPUT" "run: make gates" "hooks-O1: the note names the repair command"
assert_contains "$OUTPUT" "docs/data/gates.json" "hooks-O1: the note names the data file"
assert_equal "1" "$(printf '%s\n' "$OUTPUT" | grep -c '^{')" "hooks-O1: one JSON object"
printf '# Authoring\n\nProse, and no stamp.\n' > "$PROJECT/docs/authoring.md"
assert_quiet "docs/authoring.md" "hooks-O1: a page with no stamp"
# The prerequisite reference page is built from the relations file and the
# pages' titles at once, so the note names both, the edge writer and the gate.
printf -- '---\ntitle: Prerequisites\n---\n\n<!-- GENERATED by tools/src/gen/gen-prerequisites.ts from docs/data/relations.json. Do not edit this file. -->\n' \
  > "$PROJECT/docs/reference/prerequisites.md"
assert_advises "docs/reference/prerequisites.md" "Edit docs/data/relations.json (node scripts/kb.mjs link or unlink" "the prerequisite reference page names its source and the edge writer"
assert_contains "$OUTPUT" "or a title or description on its page" "…and the pages it reads"
assert_contains "$OUTPUT" "then run: make gen && make gate G=check-prerequisites" "…then the rebuild and the gate"
words 340 "$PROJECT/tools/CLAUDE.md"
assert_advises "tools/CLAUDE.md" "340/350" "hooks-O1: a 340-word layer against a budget of 350"

echo "== a stamp names its generator, known repair or not =="
printf '<!-- GENERATED by tools/src/gen/gen-new.ts from docs/data/new.json. Do not edit this file. -->\n' \
  > "$PROJECT/docs/reference/new.md"
advise "docs/reference/new.md"
assert_hook_advises "a generator with no registry row" "tools/src/gen/gen-new.ts"
assert_contains "$OUTPUT" "Edit the generator's source or docs/data/new.json" "…and it says to edit the source"
# A hand-written page holding a generated block stamps only the block: the
# block's freshness gate owns it, and the page is still hand-written.
printf '# Triage\n\n<!-- gate-count:start -->\n<!-- GENERATED by tools/src/gen/gen-gates.ts from docs/data/gates.json. Do not edit this paragraph. -->\n<!-- gate-count:end -->\n' \
  > "$PROJECT/docs/reference/triage.md"
assert_quiet "docs/reference/triage.md" "a page with a block stamp only"
# The stamp as text is not a stamp: quoted in a code span, or shown in a fence.
printf '# Stamps\n\nA generated page opens with `<!-- GENERATED by tools/src/gen/x.ts from docs/data/x.json. Do not edit this file. -->`.\n' \
  > "$PROJECT/docs/stamps.md"
assert_quiet "docs/stamps.md" "a hand-written page quoting the stamp in a code span"
printf '# Stamps\n\n```markdown\n<!-- GENERATED by tools/src/gen/x.ts from docs/data/x.json. Do not edit this file. -->\n```\n' \
  > "$PROJECT/docs/stamps.md"
assert_quiet "docs/stamps.md" "a hand-written page showing the stamp in a fence"
# The whole file is searched: a stamp under 40 lines of frontmatter still counts.
{
  printf -- '---\n'
  for i in $(seq 1 45); do printf 'key%s: value\n' "$i"; done
  printf -- '---\n\n<!-- GENERATED by tools/src/gen/gen-gates.ts from docs/data/gates.json. Do not edit this file. -->\n'
} > "$PROJECT/docs/reference/deep.md"
assert_advises "docs/reference/deep.md" "run: make gates" "a stamp below long frontmatter"

echo "== the hand-written pages draw no note =="
mkdir -p "$PROJECT/docs/patterns/distributed/resilience"
printf -- '---\ntitle: Circuit Breaker\nstatus: stable\n---\n\n# Circuit Breaker\n' > "$PROJECT/docs/patterns/distributed/resilience/circuit-breaker.md"
assert_quiet "docs/patterns/distributed/resilience/circuit-breaker.md" "a KB page, the source"
mkdir -p "$PROJECT/docs/concepts"
printf '# Context layering\n\nHand-written.\n' > "$PROJECT/docs/concepts/context-layering.md"
assert_quiet "docs/concepts/context-layering.md" "a hand-written concept page"
printf '# Inbox\n\n## When an entry leaves\n' > "$PROJECT/docs/inbox.md"
assert_quiet "docs/inbox.md" "the trap inbox"
printf '# Page rules\n\nHand-written.\n' > "$PROJECT/docs/reference/page-rules.md"
assert_quiet "docs/reference/page-rules.md" "a hand-written reference page"

echo "== output folders =="
mkdir -p "$PROJECT/tools/coverage"
printf '<html></html>\n' > "$PROJECT/tools/coverage/index.html"
assert_advises "tools/coverage/index.html" "make tools-test" "coverage output names its run"
# The Astro workspace's output: a built page is output, never a source.
mkdir -p "$PROJECT/site/coverage" "$PROJECT/site/dist/hazards" "$PROJECT/site/.astro" "$PROJECT/site/public" \
  "$PROJECT/site/node_modules/.astro" "$PROJECT/site/src/content/docs/patterns/caching"
printf '<html></html>\n' > "$PROJECT/site/coverage/index.html"
assert_advises "site/coverage/index.html" "Run: make site-test" "site coverage output names its run"
for f in site/dist/hazards/deadlock.html site/.astro/types.d.ts site/node_modules/.astro/data-store.json site/public/kb.js; do
  printf 'x\n' > "$PROJECT/$f"
  assert_advises "$f" "then run: make site-build" "$f is site build output"
  assert_not_contains "$OUTPUT" "(until the P5 cutover" "…and never names the HTML source"
done
printf -- '---\ntitle: Alpha\n---\n\nAlpha.\n' > "$PROJECT/site/src/content/docs/patterns/caching/alpha.md"
assert_advises "site/src/content/docs/patterns/caching/alpha.md" "tools/src/site/gen-site-docs.ts mirrors from docs/" "a mirrored page names the mirror"
assert_contains "$OUTPUT" "then run: make site-build" "…and the build"
printf -- '---\ntitle: Caching\n---\n' > "$PROJECT/site/src/content/docs/patterns/caching/index.mdx"
assert_advises "site/src/content/docs/patterns/caching/index.mdx" "tools/src/site/gen-site-hubs.ts" "a hub names its generator"
mkdir -p "$PROJECT/site/src/content/docs/map"
for f in site/src/content/docs/map/stack.mdx site/src/content/docs/map/index.mdx; do
  printf -- '---\ntitle: Map\n---\n' > "$PROJECT/$f"
  assert_advises "$f" "tools/src/site/gen-map-pages.ts" "$f names the map generator"
  assert_not_contains "$OUTPUT" "gen-site-hubs" "…never the hub generator"
done
printf -- '---\ntitle: Home\n---\n' > "$PROJECT/site/src/content/docs/index.mdx"
assert_quiet "site/src/content/docs/index.mdx" "the hand-written home page"
mkdir -p "$PROJECT/site/src/components/Head"
printf -- '---\n---\n' > "$PROJECT/site/src/components/Head/Head.astro"
assert_quiet "site/src/components/Head/Head.astro" "a site component"

echo "== a reference page rendered from a data file names the data file =="
printf -- '---\ntitle: Glossary\n---\n\n<!-- GENERATED by tools/src/gen/gen-vocabulary.ts from docs/data/glossary.json. Do not edit this file. -->\n\n# Glossary\n' \
  > "$PROJECT/docs/reference/glossary.md"
advise "docs/reference/glossary.md"
assert_hook_advises "the glossary page names its generator" "tools/src/gen/gen-vocabulary.ts"
assert_contains "$OUTPUT" "docs/data/glossary.json instead, never this file" "…and its data file, the source"
printf -- '---\ntitle: Tags\n---\n\n<!-- GENERATED by tools/src/gen/gen-taxonomy.ts from docs/data/tags.json. Do not edit this file. -->\n\n# Tags\n' \
  > "$PROJECT/docs/reference/tags.md"
advise "docs/reference/tags.md"
assert_hook_advises "the tag reference names its generator" "tools/src/gen/gen-taxonomy.ts"
assert_contains "$OUTPUT" "docs/data/tags.json instead, never this file" "…and its data file, the source"

echo "== each data file names what reads it and the command =="
mkdir -p "$PROJECT/docs/data/allow" "$PROJECT/tools/src/kb"
assert_advises "docs/data/gates.json" "make gates && make gate G=check-gates-sync && make gate G=check-json" "the gate registry"
echo '{}' > "$PROJECT/docs/data/allow/test-colocation.json"
assert_advises "docs/data/allow/test-colocation.json" "make gate G=check-test-colocation && make gate G=check-json" "the colocation allowlist"
echo '{}' > "$PROJECT/docs/data/allow/context-layers.json"
assert_advises "docs/data/allow/context-layers.json" "make gate G=check-claude-md && make gate G=check-json" "the placement allowlist"
echo '{}' > "$PROJECT/docs/data/allow/harness-shape.json"
assert_advises "docs/data/allow/harness-shape.json" "make gate G=check-harness && make gate G=check-json" "the skill-shape allowlist"
echo '{}' > "$PROJECT/docs/data/allow/vocabulary.json"
assert_advises "docs/data/allow/vocabulary.json" "make gate G=check-vocabulary && make gate G=check-json" "the vocabulary allowlist"
# The single sources: each names the gate that reads it, the json-sanity gate, and the
# rebuild where something is rendered from it.
for f in glossary:check-vocabulary:gen products:check-products: site-structure:check-site-structure:gen \
  tags:check-tags:gen content-model:check-kb-shape:gen relations:check-relations:gen learning-paths:check-learning-paths:gen; do
  name="${f%%:*}"; rest="${f#*:}"; gate="${rest%%:*}"; gen="${rest#*:}"
  echo '{}' > "$PROJECT/docs/data/$name.json"
  assert_advises "docs/data/$name.json" "make gate G=$gate" "docs/data/$name.json names the gate that reads it (data-C4)"
  assert_contains "$OUTPUT" "make gate G=check-json" "…and the json-sanity gate"
  [ -z "$gen" ] || assert_contains "$OUTPUT" "Run: make gen && " "…and the rebuild"
  assert_not_contains "$OUTPUT" "GENERATED" "…and never calls the source generated"
done
echo '{}' > "$PROJECT/docs/data/search-synonyms.json"
assert_advises "docs/data/search-synonyms.json" "make tools-test T=relevance" "the synonym bridge names the relevance fixture"
echo '{}' > "$PROJECT/docs/data/allow/prerequisites.json"
assert_advises "docs/data/allow/prerequisites.json" "make gate G=check-prerequisites && make gate G=check-json" "the orphan allowlist"
echo '{}' > "$PROJECT/docs/data/prerequisites.json"
assert_advises "docs/data/prerequisites.json" "GENERATED by tools/src/gen/gen-prerequisites.ts from docs/data/relations.json" \
  "the prerequisite graph names the generator and its source"
assert_contains "$OUTPUT" "make prerequisites && make gate G=check-prerequisites && make gate G=check-json" \
  "…the rebuild, the gate that reads it and the json-sanity gate (data-C4)"
echo '{}' > "$PROJECT/docs/data/allow/tags.json"
assert_advises "docs/data/allow/tags.json" "make gate G=check-tags && make gate G=check-json" "the retag allowlist"
echo '{}' > "$PROJECT/docs/data/allow/site-hooks.json"
assert_advises "docs/data/allow/site-hooks.json" "make gate G=check-site-hooks && make gate G=check-json" "the hook allowlist"
echo '{}' > "$PROJECT/docs/data/allow/site-e2e.json"
assert_advises "docs/data/allow/site-e2e.json" "make site-e2e && make gate G=check-json" "the e2e skip allowance"
echo '{}' > "$PROJECT/docs/data/allow/site-a11y.json"
assert_advises "docs/data/allow/site-a11y.json" "make gate G=check-site-a11y && make gate G=check-json" "the chrome-share ratchet"
echo '{}' > "$PROJECT/docs/data/allow/kb-shape.json"
assert_advises "docs/data/allow/kb-shape.json" "make gate G=check-kb-shape && make gate G=check-json" "the kb-shape ratchets (explain, costs, description)"
printf 'export {};\n' > "$PROJECT/tools/src/kb/spec.ts"
assert_advises "tools/src/kb/spec.ts" "make tools-test T=kb/spec && make gate G=check-harness-routes" "the kb.mjs command surface"
mkdir -p "$PROJECT/scripts"
printf 'export {};\n' > "$PROJECT/scripts/kb.mjs"
assert_quiet "scripts/kb.mjs" "the kb.mjs launcher"
printf 'export {};\n' > "$PROJECT/$GATE.bak"
assert_quiet "$GATE.bak" "a program source under tools/"

echo "== the real repo: every data file has its own case =="
# hooks-C5. A file added under docs/data/ without a case here fails this until
# its case lands in the hook.
CLAUDE_PROJECT_DIR="$KB_REPO_ROOT"
while IFS= read -r f; do
  [ -n "$f" ] || continue
  run_hook "$HOOK" "$(edit_payload "$KB_REPO_ROOT/$f")"
  assert_contains "$OUTPUT" "$f" "$f has an advisory case"
  # json-sanity holds every data file's source header, whatever else reads it.
  assert_contains "$OUTPUT" "make gate G=check-json" "$f names the json-sanity gate"
done <<EOF
$(cd "$KB_REPO_ROOT" && git ls-files --cached --others --exclude-standard 'docs/data/*.json' 'docs/data/**/*.json' | sort -u)
EOF
CLAUDE_PROJECT_DIR="$PROJECT"

echo "== skills, agents and rules =="
mkdir -p "$PROJECT/.claude/skills/kb-edit" "$PROJECT/.claude/rules" "$PROJECT/.claude/hooks" "$PROJECT/.claude/worktrees/w/.claude/skills/x"
for f in .claude/skills/kb-edit/SKILL.md .claude/rules/claims.md; do
  printf -- '---\ndescription: x\n---\n' > "$PROJECT/$f"
  assert_not_contains "$(advise "$f"; printf '%s' "$OUTPUT")" "lint-claude" "$f names no retired linter"
  assert_advises "$f" "make gate G=check-harness && make gate G=check-harness-routes" "$f names the two harness gates"
done
printf '#!/usr/bin/env bash\n' > "$PROJECT/.claude/hooks/x.sh"
assert_quiet ".claude/hooks/x.sh" "a hook's source"
printf 'x\n' > "$PROJECT/.claude/worktrees/w/.claude/skills/x/SKILL.md"
assert_quiet ".claude/worktrees/w/.claude/skills/x/SKILL.md" "a skill in another session's checkout"

echo "== layers against their budgets =="
words 100 "$PROJECT/tools/CLAUDE.md"
assert_quiet "tools/CLAUDE.md" "a layer with room left"
words 324 "$PROJECT/tools/CLAUDE.md"
assert_quiet "tools/CLAUDE.md" "a layer one word more than the margin below its budget"
words 325 "$PROJECT/tools/CLAUDE.md"
assert_advises "tools/CLAUDE.md" "325/350" "a layer exactly the margin below its budget (hooks-C4)"
words 400 "$PROJECT/tools/CLAUDE.md"
assert_advises "tools/CLAUDE.md" "over its 350 budget" "a layer past its budget"
advise "tools/CLAUDE.md"
assert_contains "$OUTPUT" "make gate G=check-claude-md will fail" "…says the layer gate will fail"
words 400 "$PROJECT/CLAUDE.md"
assert_quiet "CLAUDE.md" "a root layer of 400 words"
words 700 "$PROJECT/CLAUDE.md"
assert_advises "CLAUDE.md" "over its 600 budget" "a root layer of 700 words"
mkdir -p "$PROJECT/site/src/components/Term"
words 400 "$PROJECT/site/src/components/Term/CLAUDE.md"
assert_quiet "site/src/components/Term/CLAUDE.md" "a nested layer, measured in lines by the gate"
# The budgets live in the gate; change one there and the note follows.
sed 's/^export const LAYER_BUDGET = [0-9]*;/export const LAYER_BUDGET = 500;/' "$KB_REPO_ROOT/$GATE" > "$PROJECT/$GATE"
words 490 "$PROJECT/tools/CLAUDE.md"
assert_advises "tools/CLAUDE.md" "490/500" "the budget is read from the gate"
rm "$PROJECT/$GATE"
assert_quiet "tools/CLAUDE.md" "no gate to read a budget from: silent"
cp "$KB_REPO_ROOT/$GATE" "$PROJECT/$GATE"

echo "== edits it has no business with =="
run_hook "$HOOK" "$(edit_payload /etc/hosts)"
assert_hook_silent "a path outside the project"
assert_quiet "docs/reference/missing.md" "a path that does not exist"

echo "== it cannot take a session down with it =="
for input in 'not json at all' '' '[1,2,3]' '{"tool_name":"Bash","tool_input":{"command":"ls"}}' '"a string"'; do
  run_hook "$HOOK" "$input"
  assert_hook_silent "input: ${input:-<empty>}"
done
payload="$(edit_payload "$PROJECT/docs/reference/gates.md")"
path_without jq
run_hook "$HOOK" "$payload"
assert_hook_silent "no jq on PATH"
path_restore

echo "== it never touches the tree =="
before="$(tree_digest "$PROJECT")"
for f in docs/data/gates.json docs/reference/gates.md tools/CLAUDE.md docs/patterns/distributed/resilience/circuit-breaker.md CLAUDE.md; do advise "$f"; done
assert_equal "$before" "$(tree_digest "$PROJECT")" "every project file keeps its bytes"
