/**
 * The hub generator (spec kb.generation.mirror-and-hubs, hub-generator and
 * hub-order; kb.generation.output-ownership for what it may overwrite), and
 * output-ownership-O1 over the whole generation step, mirror then hubs.
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { expectFail, expectMisuse, expectPass, makeSandbox, type Sandbox } from '../lib/sandbox.js';
import { spec as mirror } from './gen-site-docs.js';
import { hubStamp, mdxText, orderHub, renderHub, spec, type Placed } from './gen-site-hubs.js';
import { docsTree, frontmatter, STRUCTURE } from './site-fixtures.js';
import { CONTENT } from './site-output.js';

let sb: Sandbox;
beforeEach(() => {
  sb = makeSandbox();
});
afterEach(() => sb.cleanup());

const card = (n: number) => ({ href: `/p${n}.html`, title: `P${n}`, description: '', status: 'stable', tags: [] });
const placed = (topics: (string | undefined)[]): Placed[] =>
  topics.map((topic, i) => ({ card: card(i + 1), rank: i + 1, ...(topic === undefined ? {} : { topic }) }));

describe('output-ownership-O1', () => {
  it('output-ownership-O1: an unstamped hub and a hand-written page keep their bytes with one note; a stamped hub loses its extra last line', async () => {
    docsTree(sb);
    expectPass(await sb.run(mirror));
    expectPass(await sb.run(spec));
    // The hazards area: a hub nobody stamped, and a hand-written page beside it.
    const hub = `${CONTENT}/hazards/index.mdx`;
    const page = `${CONTENT}/hazards/field-notes.mdx`;
    sb.write(hub, '---\ntitle: Hazards\n---\n\nA hub written by hand.\n');
    sb.write(page, '---\ntitle: Field notes\n---\n\nWritten by hand.\n');
    // The patterns area: its stamped hub, one line longer than the generator wrote it.
    const stamped = `${CONTENT}/patterns/index.mdx`;
    const fresh = sb.read(stamped);
    sb.write(stamped, `${fresh}an extra last line\n`);
    const kept = { hub: sb.read(hub), page: sb.read(page) };

    const mirrored = await sb.run(mirror);
    const hubs = await sb.run(spec);
    expectPass(mirrored);
    expectPass(hubs);
    expect(sb.read(hub)).toBe(kept.hub);
    expect(sb.read(page)).toBe(kept.page);
    expect([mirrored.err, hubs.err].filter((e) => e !== '')).toEqual([
      `[gen-site-hubs] note: ${hub} is hand-written — leaving it alone`,
    ]);
    expect(sb.read(stamped)).toBe(fresh);
  });
});

describe('orderHub', () => {
  it('groups a topic two entries share, and reorders when every entry then reads in rank order', () => {
    // Ranks P1 < P2 < P3 < P4, topics y, y, x, none (spec mirror-and-hubs, Criteria).
    expect(orderHub(placed(['y', 'y', 'x', undefined]))).toEqual([
      { label: 'y', pages: [card(1), card(2)] },
      { label: '', pages: [card(3), card(4)] },
    ]);
  });

  it('keeps the leading block when reordering would break rank order', () => {
    // Topics x, y, y, z: the block P1, P4, then group y (P2, P3).
    expect(orderHub(placed(['x', 'y', 'y', 'z']))).toEqual([
      { label: '', pages: [card(1), card(4)] },
      { label: 'y', pages: [card(2), card(3)] },
    ]);
  });

  it('sorts by rank first, names a group by its label, and has no block when every entry is grouped', () => {
    const entries = placed(['t', 't']).reverse();
    expect(orderHub(entries, (t) => `Topic ${t}`)).toEqual([{ label: 'Topic t', pages: [card(1), card(2)] }]);
  });
});

describe('the hub page', () => {
  it('opens with the frontmatter, then the stamp, the import at the folder’s depth, the intro and the entries', () => {
    const area = STRUCTURE.areas[1] as (typeof STRUCTURE.areas)[number];
    const text = renderHub(area, 'patterns/caching', [{ label: '', pages: [card(1)] }]);
    expect(text.split('\n').slice(0, 13)).toEqual([
      '---',
      'title: Caching',
      'description: Keeping answers close',
      'area: caching',
      'owner: Oleksandr Derechei',
      'tags: [caching, performance]',
      // Every input page declares a status, a hub included (maturity-C3).
      'status: stable',
      'source: generated by tools/src/site/gen-site-hubs.ts from patterns/caching/ frontmatter',
      '---',
      '',
      hubStamp('patterns/caching/ frontmatter'),
      '',
      "import SectionHub from '../../../../components/SectionHub/SectionHub.astro';",
    ]);
    expect(hubStamp('x')).toBe('{/* GENERATED by tools/src/site/gen-site-hubs.ts from x. Do not edit this file. */}');
  });

  it('writes an intro MDX would read as markup as text', () => {
    expect(mdxText('a <b> {c} & d')).toBe('a &lt;b> \\{c\\} &amp; d');
  });
});

describe('gen-site-hubs', () => {
  it('writes one hub per area with children, entries from each page’s frontmatter, a nested area listed ungrouped', async () => {
    docsTree(sb);
    const r = await sb.run(spec);
    expectPass(r);
    expect(r.out).toBe('[gen-site-hubs] wrote 3 hub pages from docs/data/site-structure.json');
    const caching = sb.read(`${CONTENT}/patterns/caching/index.mdx`);
    // alpha's topic is caching (shared with none), beta's resilience: no group forms.
    expect(caching).toContain(
      '<SectionHub groups={[{"label":"","pages":[' +
        '{"href":"/patterns/caching/alpha.html","title":"Alpha","description":"What Alpha does","status":"stable","slug":"alpha","tags":["caching","performance"]},' +
        '{"href":"/patterns/caching/beta.html","title":"Beta","description":"What Beta does","status":"stable","slug":"beta","tags":["resilience"]}]}]} />',
    );
    const patterns = sb.read(`${CONTENT}/patterns/index.mdx`);
    expect(patterns).toContain(
      '{"href":"/patterns/caching.html","title":"Caching","description":"Keeping answers close","status":"stable","tags":["caching","performance"]}',
    );
    expect(sb.exists(`${CONTENT}/hazards/index.mdx`)).toBe(true);
  });

  it('marks a page its frontmatter calls a favourite, and no other', async () => {
    docsTree(sb);
    sb.write('docs/patterns/caching/beta.md', `${frontmatter('Beta', { favourite: 'true' })}\n# Beta\n\nBeta.\n`);
    expectPass(await sb.run(spec));
    const caching = sb.read(`${CONTENT}/patterns/caching/index.mdx`);
    expect(caching).toContain('"slug":"beta","tags":["caching","performance"],"favourite":true}');
    expect(caching).toContain('"slug":"alpha","tags":["caching","performance"]}');
  });

  it('groups two pages that share a topic under the topic’s label', async () => {
    docsTree(sb);
    sb.write('docs/patterns/caching/beta.md', sb.read('docs/patterns/caching/beta.md').replace('tags: [resilience]', 'tags: [caching]'));
    expectPass(await sb.run(spec));
    expect(sb.read(`${CONTENT}/patterns/caching/index.mdx`)).toContain('{"label":"Caching topic","pages":[');
  });

  it('groups nothing when the tag file cannot be read', async () => {
    docsTree(sb);
    sb.write('docs/patterns/caching/beta.md', sb.read('docs/patterns/caching/beta.md').replace('tags: [resilience]', 'tags: [caching]'));
    sb.write('docs/data/tags.json', 'not json');
    expectPass(await sb.run(spec));
    expect(sb.read(`${CONTENT}/patterns/caching/index.mdx`)).toContain('groups={[{"label":"","pages":[');
  });

  it('writes no hub for a generated area or one with no children, listing the generated one last and the empty one nowhere', async () => {
    const structure = {
      areas: [
        ...STRUCTURE.areas,
        { id: 'patterns-map', label: 'Map', nestUnder: 'patterns', generated: 'gen-map', hub: STRUCTURE.areas[0]?.hub, pages: [] },
        { id: 'patterns-empty', label: 'Empty', nestUnder: 'patterns', hub: STRUCTURE.areas[0]?.hub, pages: [] },
        { id: 'patterns-group', label: 'Group', nestUnder: 'patterns', hub: STRUCTURE.areas[0]?.hub, pages: [] },
        {
          id: 'patterns-group-leaf',
          label: 'Leaf',
          nestUnder: 'patterns-group',
          hub: STRUCTURE.areas[0]?.hub,
          pages: [{ slug: 'delta', label: 'Delta', source: 'docs/patterns/delta.md', route: '/patterns/delta.html' }],
        },
      ],
    };
    docsTree(sb, structure as typeof STRUCTURE);
    sb.write('docs/patterns/delta.md', '---\ntitle: Delta\n---\n\n# Delta\n');
    expectPass(await sb.run(spec));
    // An area with no pages of its own, holding one that has some, opens.
    expect(sb.read(`${CONTENT}/patterns/index.mdx`)).toContain('"href":"/patterns/group.html"');
    expect(sb.exists(`${CONTENT}/patterns/map/index.mdx`)).toBe(false);
    expect(sb.exists(`${CONTENT}/patterns/empty/index.mdx`)).toBe(false);
    const patterns = sb.read(`${CONTENT}/patterns/index.mdx`);
    expect(patterns.indexOf('/patterns/caching.html')).toBeLessThan(patterns.indexOf('/patterns/map.html'));
    expect(patterns).not.toContain('/patterns/empty.html');
  });

  it('writes no hub for a link or an unpublished (`none`) area, and no parent lists one', async () => {
    const hub = STRUCTURE.areas[0]?.hub;
    const structure = {
      areas: [
        ...STRUCTURE.areas,
        { id: 'patterns-solo', label: 'Solo', nav: 'link', nestUnder: 'patterns', hub, pages: [{ slug: 'solo', label: 'Solo', source: 'docs/patterns/solo.md', route: '/patterns/solo.html' }] },
        { id: 'patterns-off', label: 'Off', nav: 'none', nestUnder: 'patterns', hub, pages: [{ slug: 'off', label: 'Off', source: 'docs/patterns/off.md', route: '/patterns/off.html' }] },
        { id: 'quiet', label: 'Quiet', nav: 'none', hub, pages: [{ slug: 'quiet', label: 'Quiet', source: 'docs/patterns/quiet.md', route: '/quiet/quiet.html' }] },
      ],
    };
    docsTree(sb, structure as typeof STRUCTURE);
    expectPass(await sb.run(spec));
    expect(sb.exists(`${CONTENT}/patterns/solo/index.mdx`)).toBe(false);
    expect(sb.exists(`${CONTENT}/patterns/off/index.mdx`)).toBe(false);
    expect(sb.exists(`${CONTENT}/quiet/index.mdx`)).toBe(false);
    const patterns = sb.read(`${CONTENT}/patterns/index.mdx`);
    expect(patterns).not.toContain('/patterns/solo.html');
    expect(patterns).not.toContain('/patterns/off.html');
    expect(sb.exists(`${CONTENT}/hazards/index.mdx`)).toBe(true);
  });

  it('reads a missing description, status and tags as empty, stable and none', async () => {
    docsTree(sb);
    sb.write('docs/hazards/gamma.md', '---\ntitle: Gamma\n---\n\n# Gamma\n');
    expectPass(await sb.run(spec));
    expect(sb.read(`${CONTENT}/hazards/index.mdx`)).toContain(
      '{"href":"/hazards/gamma.html","title":"Gamma","description":"","status":"stable","slug":"gamma","tags":[]}',
    );
  });

  it('names a group by the topic’s id when the tag file gives it no label', async () => {
    docsTree(sb);
    sb.write('docs/patterns/caching/alpha.md', sb.read('docs/patterns/caching/alpha.md').replace('tags: [caching, performance]', 'tags: [resilience]'));
    expectPass(await sb.run(spec));
    expect(sb.read(`${CONTENT}/patterns/caching/index.mdx`)).toContain('{"label":"resilience","pages":[');
  });

  it('names a page whose source is missing as one with no title', async () => {
    docsTree(sb);
    sb.rm('docs/hazards/gamma.md');
    expectFail(await sb.run(spec), 'docs/hazards/gamma.md: has no title');
  });

  it('names a child with no title, writing nothing', async () => {
    docsTree(sb);
    sb.write('docs/hazards/gamma.md', '---\ndescription: d\n---\n\n# Gamma\n');
    const r = await sb.run(spec);
    expectFail(r);
    expect(r.err).toBe('[gen-site-hubs] FAIL docs/hazards/gamma.md: has no title — the hazards hub lists every page by its title');
    expect(sb.exists(CONTENT)).toBe(false);
  });

  it('leaves an unstamped hand-written hub with one note, rewrites a stamped one, deletes a stamped one whose area left', async () => {
    docsTree(sb);
    expectPass(await sb.run(spec));
    sb.write(`${CONTENT}/hazards/index.mdx`, 'hand-written hub\n');
    const stamped = `${CONTENT}/patterns/index.mdx`;
    const fresh = sb.read(stamped);
    sb.write(stamped, `${fresh}an extra last line\n`);
    sb.write(`${CONTENT}/old/index.mdx`, `${hubStamp('old/ frontmatter')}\n`);
    sb.write(`${CONTENT}/kept/index.mdx`, 'an ignored file of no generator: not this one’s to delete\n');
    const r = await sb.run(spec);
    expectPass(r);
    expect(r.err).toBe(`[gen-site-hubs] note: ${CONTENT}/hazards/index.mdx is hand-written — leaving it alone`);
    expect(sb.read(`${CONTENT}/hazards/index.mdx`)).toBe('hand-written hub\n');
    expect(sb.read(stamped)).toBe(fresh);
    expect(sb.exists(`${CONTENT}/old`)).toBe(false);
    expect(sb.exists(`${CONTENT}/kept/index.mdx`)).toBe(true);
  });

  it('exits 2 on --check or any unknown argument, writing nothing', async () => {
    docsTree(sb);
    const before = sb.snapshot();
    expectMisuse(await sb.run(spec, ['--check']));
    expect(sb.snapshot()).toEqual(before);
  });
});
