/**
 * kb.mjs v2 end to end over the fixture tree (`writeKbFixture` in
 * tools/src/lib/fixtures.ts): every read command, text and --json, the
 * argument rules and the failures, driven in-process through `run`. The real
 * tree is parity.test.ts's.
 */

import path from 'node:path';
import { PassThrough } from 'node:stream';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';

import { writeKbFixture } from '../lib/fixtures.js';
import { makeSandbox, type Sandbox } from '../lib/sandbox.js';

import { main, quietOnClose, run } from './cli.js';
import { Corpus } from './corpus.js';
import { today } from './data.js';

let sb: Sandbox;
let root: string;

beforeAll(() => {
  sb = makeSandbox();
  root = sb.dir;
  writeKbFixture(root);
});
afterAll(() => sb.cleanup());

interface Ran {
  readonly code: number;
  readonly out: string;
  readonly err: string;
}

async function kb(at: string | Corpus, ...argv: string[]): Promise<Ran> {
  const out: string[] = [];
  const err: string[] = [];
  const code = await run(argv, { out: (l) => out.push(l), err: (l) => err.push(l) }, at);
  return { code, out: out.join('\n'), err: err.join('\n') };
}
const json = async (...argv: string[]): Promise<Record<string, unknown>> => {
  const r = await kb(root, ...argv, '--json');
  expect(r.code, r.err).toBe(0);
  return JSON.parse(r.out) as Record<string, unknown>;
};

describe('the surface', () => {
  it('prints the usage with no command, and exits 0', async () => {
    const r = await kb(root);
    expect(r.code).toBe(0);
    expect(r.out).toContain('Reading:');
    expect(r.out).toContain('kb.mjs get <id> [--block <b>]');
    expect(r.out).not.toContain('register');
  });

  it('prints the usage and exits 1 on a command it does not know', async () => {
    const r = await kb(root, 'frobnicate');
    expect(r.code).toBe(1);
    expect(r.out).toContain('Writing (authoring');
  });

  it('hands a write command to its writer, which refuses a page the converter stamped', async () => {
    const own = makeSandbox();
    try {
      writeKbFixture(own.dir);
      const page = 'docs/patterns/distributed/resilience/breaker.md';
      own.write(page, own.read(page).replace('a converter from', 'tools/src/migrate/html-to-md.ts from'));
      const before = own.snapshot();
      const r = await kb(own.dir, 'set', 'breaker', '--favourite', 'false');
      expect(r).toEqual({
        code: 1,
        out: '',
        err: `${page} is generated by tools/src/migrate/html-to-md.ts from site/x.html (its stamp says so): edit site/x.html, then run make gen`,
      });
      expect(own.snapshot()).toEqual(before);
    } finally {
      own.cleanup();
    }
  });

  it('dates a data file with today when the caller names no day', async () => {
    const own = makeSandbox();
    try {
      writeKbFixture(own.dir);
      const r = await kb(own.dir, 'link', 'queue', 'combines-with', 'retry');
      expect(r.code, r.err).toBe(0);
      expect((JSON.parse(own.read('docs/data/relations.json')) as { updated: string }).updated).toBe(today());
    } finally {
      own.cleanup();
    }
  });

  it('refuses register and level, which are retired', async () => {
    const r = await kb(root, 'register', 'breaker', 'x', 'advanced');
    expect(r.code).toBe(1);
    expect(r.err).toContain('register is retired');
    expect(await kb(root, 'level', 'breaker', 'x', 'advanced')).toEqual({ code: 1, out: '', err: 'reading levels were retired: a page reads at one depth' });
  });

  it('refuses a --level flag, whatever its value, before anything else', async () => {
    for (const value of ['guru', 'basic']) {
      const r = await kb(root, 'get', 'breaker', '--level', value);
      expect(r).toEqual({ code: 1, out: '', err: '--level is gone: reading levels were retired, a page reads at one depth' });
    }
  });

  it('names an unknown id, with the ids that contain it', async () => {
    const r = await kb(root, 'get', 'break');
    expect(r.code).toBe(1);
    expect(r.err).toBe('unknown id: break\ndid you mean: breaker');
    expect((await kb(root, 'related')).err).toBe('unknown id: (none given)');
    expect((await kb(root, 'get', 'zzz')).err).toBe('unknown id: zzz');
  });

  it('rethrows what is not a lookup failure', async () => {
    const broken = makeSandbox();
    try {
      writeKbFixture(broken.dir);
      broken.write('docs/data/content-model.json', '{"kinds": []}');
      await expect(kb(broken.dir, 'ls')).rejects.toThrow(TypeError);
    } finally {
      broken.cleanup();
    }
  });

  it('reports a data file it cannot read as a failed lookup', async () => {
    const broken = makeSandbox();
    try {
      writeKbFixture(broken.dir);
      broken.write('docs/data/site-structure.json', '[]');
      expect((await kb(broken.dir, 'ls')).err).toBe('docs/data/site-structure.json is not a JSON object');
      broken.write('docs/data/site-structure.json', '{');
      expect((await kb(broken.dir, 'ls')).err).toMatch(/^cannot read docs\/data\/site-structure.json: /);
    } finally {
      broken.cleanup();
    }
  });
});

describe('get', () => {
  it('prints the whole page: the header, then every block', async () => {
    const r = await kb(root, 'get', 'breaker');
    expect(r.code).toBe(0);
    expect(r.out.split('\n').slice(0, 5)).toEqual([
      '# Breaker  [breaker]',
      'pattern · distributed · distributed-resilience',
      'essence: The breaker page',
      'path: patterns/distributed/resilience/breaker.html',
      'source: docs/patterns/distributed/resilience/breaker.md',
    ]);
    expect(r.out).toContain('\n## tradeoffs\n\nPROS\n- [tradeoffs-pro-1] Fails fast.\n- [tradeoffs-pro-2] Frees threads.\n\nCONS\n');
    expect(r.out).toContain('\n## relationships\n\nCombines with:\n- Retry [retry] — Retry transient errors\n\nPrevents:\n- Storm [storm] — Fails fast');
  });

  it('prints a band that is its own group once', async () => {
    expect((await kb(root, 'get', 'queue')).out.split('\n')[1]).toBe('pattern · messaging');
    expect((await kb(root, 'get', 'storm')).out.split('\n')[1]).toBe('hazard · hazard');
  });

  it('prints one block with no header', async () => {
    const r = await kb(root, 'get', 'breaker', '--block', 'variations');
    expect(r.out).toBe(
      '\n## variations\n\n- [variations-item-1] **Count-based**: Trip after N failures.\n\n- [variations-item-2] **Retry guarded**: Wraps a retry.\n- [variations-item-3] A plain variation with no name.',
    );
  });

  it('names the blocks a page has when asked for one it lacks', async () => {
    const r = await kb(root, 'get', 'quick', '--block', 'wild');
    expect(r.code).toBe(1);
    expect(r.err).toBe('no block "wild" on quick. has: description, explain, rationale, applying, overreach, relationships');
  });

  it('names no block after what every object inherits', async () => {
    for (const name of ['constructor', 'toString', '__proto__', 'hasOwnProperty']) {
      for (const json of [[], ['--json']]) {
        const r = await kb(root, 'get', 'quick', '--block', name, ...json);
        expect(r, name).toEqual({ code: 1, out: '', err: `no block "${name}" on quick. has: description, explain, rationale, applying, overreach, relationships` });
      }
    }
  });

  it('keeps the mermaid source only with --diagrams', async () => {
    expect((await kb(root, 'get', 'breaker', '--block', 'structure')).out).toBe('\n## structure\n\n_How does the gate stop calls?_\n\n_The states._');
    const d = (await kb(root, 'get', 'breaker', '--block', 'structure', '--diagrams')).out;
    expect(d).toContain('```mermaid\nflowchart LR\n  A --> B\n');
  });

  it('prints every block whole: the explain paragraph and its example, the nested usage items, the empty relationships block', async () => {
    const blocks = (await json('get', 'breaker'))['blocks'] as Record<string, string>;
    expect(blocks['explain']).toMatch(/^Tune it against a slow dependency\. .*\n- \[explain-li-1\] Latency\. Every call pays for one extra hop\.\n- \[explain-li-2\] Upkeep\. .*\n\nEXAMPLE\n\nCheckout calls a fraud check/);
    expect(blocks['usage']).toContain('- [usage-when-1] You call a remote service.\n  - Nested detail one.\n  - Nested detail two.\n- [usage-when-2]');
    expect(Object.keys((await json('get', 'queue'))['blocks'] as object)).toContain('relationships');
  });

  it('prints the facts, the relations and the themes as JSON', async () => {
    const j = await json('get', 'breaker');
    expect(j).toMatchObject({
      id: 'breaker',
      name: 'Breaker',
      kind: 'pattern',
      band: 'distributed',
      group: 'distributed-resilience',
      essence: 'The breaker page',
      path: 'patterns/distributed/resilience/breaker.html',
      source: 'docs/patterns/distributed/resilience/breaker.md',
      relations: [
        { type: 'combines-with', to: 'retry', label: 'Combines with', note: 'Retry transient errors' },
        { type: 'prevents-hazard', to: 'storm', label: 'Prevents', note: 'Fails fast' },
      ],
      themes: [{ id: 'steady', name: 'Steady', role: 'Stop hammering it', href: 'themes/steady.html' }],
    });
    expect(j).not.toHaveProperty('level');
    expect(j).not.toHaveProperty('levels');
  });

  it('dumps the writer-owned blocks in the writers’ own shape', async () => {
    const w = await json('get', 'breaker', '--block', 'wild');
    expect(w['items']).toEqual({
      wild: [
        { id: 'opossum', name: 'opossum', note: 'The Node breaker: <code>errorThresholdPercentage</code> &amp; more.' },
        { id: 'hystrix', name: 'Hystrix', note: 'The JVM one.', href: 'https://github.com/Netflix/Hystrix' },
        { id: 'bare', name: '', note: 'A bare example with no name.' },
      ],
    });
    const p = await json('get', 'breaker', '--block', 'production');
    expect(p['items']).toEqual({
      production: {
        knobs: [
          { label: 'Failure threshold', note: 'The count at which it opens (<code>failureRateThreshold</code>).' },
          { label: 'Window', note: 'Measured over time.' },
          { label: '', note: 'A knob with no label.' },
        ],
        signals: [{ label: 'State', note: 'Closed or open.' }],
        failures: [{ label: 'Flapping', note: 'Opens and closes.' }],
        checklist: [{ text: 'Every call has a timeout' }, { text: 'Operators can <strong>force</strong> it' }],
      },
    });
    const e = await json('get', 'breaker', '--block', 'explain');
    expect(e['items']).toEqual({
      explain: {
        text: expect.stringMatching(/^Tune it against a slow dependency\. /),
        costs: [
          { lead: 'Latency.', note: 'Every call pays for one extra hop.' },
          { lead: 'Upkeep.', note: 'Someone owns the counters and the thresholds.' },
        ],
        example: expect.stringMatching(/^Checkout calls a fraud check/),
      },
    });
    // All three at once on the whole page; none on a block that is none of them.
    expect(Object.keys((await json('get', 'breaker'))['items'] as object)).toEqual(['wild', 'production', 'explain']);
    expect(await json('get', 'breaker', '--block', 'usage')).not.toHaveProperty('items');
  });

  it('renders every construct of a design', async () => {
    const r = await kb(root, 'get', 'shortener');
    expect(r.out).toContain('- [requirements-nfr-1] Scale\n  - A million a day.\n  - Reads dominate.');
    expect(r.out).toContain('- [entities-li-1] Link — The mapping.\n\nLink table\n\n```sql\ncreate table link (code text primary key);\n```');
    expect(r.out).toContain('An API in front of a cache.\n| Component | Role |\n| API | Takes writes |\n| Cache | Serves reads |');
    expect(r.out).toContain('1 · CODES THAT NEVER COLLIDE → NFR: SCALE\n\nUse a counter.\n\nWhy hashing fails\n\nTwo links can share a hash.');
    expect(r.out).toContain('Serves reads');
  });

  it('prints a relationship row whose link names no page with no slug', async () => {
    const odd = makeSandbox();
    try {
      writeKbFixture(odd.dir);
      odd.write('docs/hazards/storm.md', odd.read('docs/hazards/storm.md').replace('(../patterns/distributed/resilience/breaker.md) — Fails fast', '(../patterns/gone.md) — Fails fast'));
      expect((await kb(odd.dir, 'get', 'storm', '--block', 'relationships')).out).toBe('\n## relationships\n\nMitigated by:\n- Breaker — Fails fast');
    } finally {
      odd.cleanup();
    }
  });

  it('renders a theme: tour steps, the decide table, sibling rows', async () => {
    const r = await kb(root, 'get', 'steady');
    expect(r.out).toContain('## tour\n\nBREAKER\n\nTrip open after enough failures.\n\nRETRY\n\nTry again, briefly.');
    expect(r.out).toContain('| Ride out a blip | Retry |');
    expect(r.out).toContain('## siblings\n\n- Loop — The other theme.\n- A sibling with no link.');
    // Kind is the folder: a theme filed in a designs tier is still a theme.
    expect((await json('get', 'loop'))['kind']).toBe('theme');
  });
});

describe('related', () => {
  it('groups the typed neighbours by label and names the themes', async () => {
    const r = await kb(root, 'related', 'breaker');
    expect(r.out).toBe(
      '# Breaker — 2 relations\n\nCombines with:\n  retry — Retry transient errors\nPrevents:\n  storm — Fails fast\n\nIn themes:\n  steady — Stop hammering it',
    );
    expect((await kb(root, 'related', 'storm')).out).toBe('# Storm — 1 relations\n\nMitigated by:\n  breaker — Fails fast');
  });

  it('prints an empty note without its dash, and the sides as JSON', async () => {
    const quiet = makeSandbox();
    try {
      writeKbFixture(quiet.dir);
      quiet.write('docs/data/relations.json', JSON.stringify({ relations: [{ a: 'quick', verb: 'combines-with', b: 'retry', note_a: '', note_b: '' }] }));
      expect((await kb(quiet.dir, 'related', 'quick')).out).toBe('# Quick — 1 relations\n\nCombines with:\n  retry');
    } finally {
      quiet.cleanup();
    }
    expect(JSON.parse((await kb(root, 'related', 'retry', '--json')).out)).toEqual([
      { type: 'combines-with', to: 'breaker', label: 'Combines with', note: 'Trip on sustained errors' },
    ]);
  });
});

describe('ls and find listings', () => {
  it('lists every page of the seven kinds, by kind then reading order', async () => {
    const r = await kb(root, 'ls');
    const ids = r.out.split('\n').filter((l) => /^[a-z]/.test(l) && !l.includes('entries.')).map((l) => l.split(' ')[0]);
    expect(ids).toEqual(['breaker', 'retry', 'queue', 'storm', 'loop', 'steady', 'quick', 'shortener', 'queues', 'brokers']);
    expect(r.out).toContain('breaker                      The breaker page');
    expect(r.out.endsWith('\n10 entries.')).toBe(true);
  });

  it('filters by band and kind, and prints the catalog rows as JSON', async () => {
    const rows = JSON.parse((await kb(root, 'ls', '--band', 'distributed', '--json')).out) as { id: string }[];
    expect(rows.map((r) => r.id)).toEqual(['breaker', 'retry']);
    expect(rows[0]).toEqual({
      id: 'breaker',
      name: 'Breaker',
      kind: 'pattern',
      band: 'distributed',
      essence: 'The breaker page',
      path: 'patterns/distributed/resilience/breaker.html',
      favourite: true,
      aliases: ['CB', 'fuse'],
      tags: ['resilience', 'latency'],
      solves: ['my threads hang on a dead dependency', 'one failing call, and the whole service falls'],
      hasExample: true,
      hasExplain: true,
    });
    expect(rows[1]).not.toHaveProperty('hasExample');
    // Reading order: the designs tier that files `loop` comes before the themes area.
    expect(JSON.parse((await kb(root, 'ls', '--kind', 'theme', '--json')).out).map((r: { id: string }) => r.id)).toEqual(['loop', 'steady']);
  });

  it('lists a page with no tags without a tags key, and never under a tag filter', async () => {
    const bare = makeSandbox();
    try {
      writeKbFixture(bare.dir);
      bare.write('docs/principles/quick.md', bare.read('docs/principles/quick.md').replace('tags: [resilience, latency]\n', ''));
      const rows = JSON.parse((await kb(bare.dir, 'ls', '--kind', 'principle', '--json')).out) as object[];
      expect(rows[0]).not.toHaveProperty('tags');
      expect((await kb(bare.dir, 'find', '--tag', 'latency')).out).not.toContain('quick');
    } finally {
      bare.cleanup();
    }
  });

  it('treats a find with filters and no query as a listing, and refuses one with neither', async () => {
    expect((await kb(root, 'find', '--tag', 'messaging')).out).toBe('queue                        The queue page\nqueues                       The queues page\n\n2 entries.');
    expect(JSON.parse((await kb(root, 'find', '--kind', 'hazard', '--json')).out)).toHaveLength(1);
    expect(JSON.parse((await kb(root, 'find', '--band', 'messaging', '--json')).out)).toHaveLength(1);
    const r = await kb(root, 'find');
    expect(r.code).toBe(1);
    expect(r.err).toBe('usage: kb.mjs find <query…> [--tag T] [--band B] [--kind K]');
  });
});

describe('find', () => {
  it('ranks by name and symptom, and shows the line that matched', async () => {
    const r = await kb(root, 'find', 'threads', 'hang', 'dependency');
    expect(r.code).toBe(0);
    expect(r.out.split('\n')[0]).toBe('breaker  (pattern/distributed)  — The breaker page');
    expect(r.out).toContain('    ↳ ');
    expect(r.out).toMatch(/\n\d+ match\(es\)\. Next: kb\.mjs get <id> \[--block usage\]$/);
  });

  it('answers an exact alias first, and caps the matches at --n', async () => {
    const j = JSON.parse((await kb(root, 'find', 'kafka', '--json')).out) as { id: string; why: string | null }[];
    expect(j[0]?.id).toBe('brokers');
    expect(JSON.parse((await kb(root, 'find', 'the', 'page', '--n', '2', '--json')).out)).toHaveLength(2);
  });

  it('reads --n 0 or an --n that is no number as no cap, as scripts/kb.mjs does', async () => {
    const all = JSON.parse((await kb(root, 'find', 'the', 'page', '--n', '100', '--json')).out) as unknown[];
    expect(all.length).toBeGreaterThan(8);
    for (const n of ['0', 'abc']) {
      expect(JSON.parse((await kb(root, 'find', 'the', 'page', '--n', n, '--json')).out), n).toHaveLength(all.length);
      const b = JSON.parse((await kb(root, 'brief', 'the', 'page', '--n', n, '--json')).out) as { matches: unknown[] };
      expect(b.matches, n).toHaveLength(all.length);
    }
  });

  it('says so when nothing matches', async () => {
    expect((await kb(root, 'find', 'zebra', 'unicorn')).out).toBe('no match for "zebra unicorn"');
  });

  it('searches every line of a page, and refuses a --level flag', async () => {
    const all = JSON.parse((await kb(root, 'find', 'seniors', '--json')).out) as { id: string }[];
    expect(all.map((n) => n.id)).toContain('breaker');
    expect((await kb(root, 'find', 'seniors', '--level', 'basic')).code).toBe(1);
  });

  it('cuts a long matched line at 150 characters', async () => {
    const long = makeSandbox();
    try {
      writeKbFixture(long.dir);
      const text = long.read('docs/principles/quick.md').replace('Faults stay near their cause.', `Faults stay near their cause ${'and zebras roam '.repeat(12)}.`);
      long.write('docs/principles/quick.md', text);
      const r = await kb(long.dir, 'find', 'zebras');
      expect(r.out).toMatch(/↳ Faults stay near .{120,}…\n/);
    } finally {
      long.cleanup();
    }
  });
});

describe('brief', () => {
  it('bundles the matches, the governing theme’s decide table and the top hits’ neighbours', async () => {
    const r = await kb(root, 'brief', 'dead', 'dependency', 'threads');
    expect(r.code).toBe(0);
    expect(r.out.startsWith('# brief: dead dependency threads\n\n## matches\n\nbreaker  (pattern/distributed)')).toBe(true);
    expect(r.out).toContain('\n## theme: steady — decide\n\n| If you need… | Reach for |');
    expect(r.out).toContain('\n## related: breaker\n\nCombines with:\n  retry — Retry transient errors');
    expect(r.out.endsWith('\nNext: kb.mjs get <id> --block usage|tradeoffs')).toBe(true);
  });

  it('gives the neighbours of exactly the top three hits that are not themes', async () => {
    const sizes: number[] = [];
    for (const q of [['dead', 'dependency', 'threads'], ['steady'], ['the', 'page'], ['breaker', 'retry', 'queue', '--kind', 'pattern'], ['queue', '--n', '2']]) {
      const b = JSON.parse((await kb(root, 'brief', ...q, '--json')).out) as { matches: { id: string; kind: string }[]; related: Record<string, unknown[]> };
      const want = b.matches.slice(0, 3).filter((m) => m.kind !== 'theme').map((m) => m.id);
      expect(Object.keys(b.related), q.join(' ')).toEqual(want);
      sizes.push(want.length);
    }
    // Fewer than three when a theme is among the top three or the list is short; none when all are themes.
    expect(sizes).toEqual([1, 0, 2, 3, 2]);
  });

  it('takes a theme among the hits, or the one named, as JSON', async () => {
    const hit = JSON.parse((await kb(root, 'brief', 'steady', '--json')).out) as { theme: { id: string }; related: object };
    expect(hit.theme.id).toBe('steady');
    expect(Object.keys(hit.related)).not.toContain('steady');
    const named = JSON.parse((await kb(root, 'brief', 'queue', '--theme', 'loop', '--json')).out) as { query: string; theme: { id: string; decide: string } };
    expect(named.query).toBe('queue');
    expect(named.theme).toEqual({ id: 'loop', decide: '| If you need… | Reach for |\n| Hold work | Queue |' });
  });

  it('answers no theme when none governs, and says so for a theme with no decide table', async () => {
    const none = JSON.parse((await kb(root, 'brief', 'brokers', 'kafka', '--json')).out) as { theme: unknown };
    expect(none.theme).toBeNull();
    const bare = makeSandbox();
    try {
      writeKbFixture(bare.dir);
      bare.write('docs/themes/loop.md', bare.read('docs/themes/loop.md').replace(/## When to reach for what[^]*?(?=## Related)/, ''));
      const r = await kb(bare.dir, 'brief', 'queue', '--theme', 'loop');
      expect(r.out).toContain('## theme: loop — decide\n\n(no decide block on this theme)');
    } finally {
      bare.cleanup();
    }
  });

  it('votes for the theme most of the top hits belong to, and prints no theme section when none does', async () => {
    const vote = JSON.parse((await kb(root, 'brief', 'breaker', 'retry', 'queue', '--kind', 'pattern', '--json')).out) as { matches: { id: string }[]; theme: { id: string } };
    expect(vote.matches.map((m) => m.id).sort()).toEqual(['breaker', 'queue', 'retry']);
    expect(vote.theme.id).toBe('steady');
    const none = (await kb(root, 'brief', 'brokers', 'kafka')).out;
    expect(none).not.toContain('## theme:');
  });

  it('refuses a missing query and a theme id that is not a theme; says so when nothing matches', async () => {
    expect(await kb(root, 'brief')).toEqual({ code: 1, out: '', err: 'usage: kb.mjs brief <query…> [--theme <id>] [--tag T] [--band B] [--kind K] [--n 5]' });
    expect((await kb(root, 'brief', 'queue', '--theme', 'breaker')).err).toBe('not a theme id: breaker');
    expect((await kb(root, 'brief', 'zebra', 'unicorn')).out).toBe('no match for "zebra unicorn"');
  });
});

describe('backlinks and refs', () => {
  it('lists typed inbound edges and the prose mentions both ways', async () => {
    const j = JSON.parse((await kb(root, 'backlinks', 'retry', '--json')).out) as Record<string, unknown>;
    expect(j).toEqual({
      id: 'retry',
      inbound: [{ from: 'breaker', type: 'combines-with', label: 'Combines with', note: 'Retry transient errors' }],
      mentionedBy: [],
      mentions: [],
    });
    const q = JSON.parse((await kb(root, 'backlinks', 'queue', '--json')).out) as Record<string, unknown>;
    expect(q['mentionedBy']).toEqual(['breaker']);
    const t = (await kb(root, 'backlinks', 'breaker')).out;
    expect(t).toBe(
      '# Breaker — 2 inbound relation(s)\n\n  retry  [combines-with] — Trip on sustained errors\n  storm  [mitigated-by] — Fails fast\nMentions in its own prose: queue',
    );
    expect((await kb(root, 'backlinks', 'queue')).out).toBe('# Queue — 0 inbound relation(s)\n\n\nMentioned in prose by: breaker');
  });

  it('prints an inbound edge with no note without its dash', async () => {
    const quiet = makeSandbox();
    try {
      writeKbFixture(quiet.dir);
      quiet.write('docs/data/relations.json', JSON.stringify({ relations: [{ a: 'quick', verb: 'combines-with', b: 'retry', note_a: '', note_b: '' }] }));
      // With no edge between them, breaker and retry now mention each other in prose.
      expect((await kb(quiet.dir, 'backlinks', 'retry')).out).toBe(
        '# Retry — 1 inbound relation(s)\n\n  quick  [combines-with]\n\nMentioned in prose by: breaker\nMentions in its own prose: breaker',
      );
    } finally {
      quiet.cleanup();
    }
  });

  it('reports what a page points at, carrier by carrier', async () => {
    const j = JSON.parse((await kb(root, 'refs', 'breaker', '--json')).out) as Record<string, unknown>;
    expect(j).toEqual({
      id: 'breaker',
      path: 'patterns/distributed/resilience/breaker.html',
      source: 'docs/patterns/distributed/resilience/breaker.md',
      relations: [
        { rel: 'combines-with', to: 'retry' },
        { rel: 'prevents-hazard', to: 'storm' },
      ],
      members: [],
      fluency: ['steady'],
      proseLinks: ['retry', 'storm', 'queue'],
      clicks: ['retry'],
      untyped: ['queue'],
    });
    const theme = JSON.parse((await kb(root, 'refs', 'loop', '--json')).out) as Record<string, unknown>;
    expect(theme['members']).toEqual([
      { to: 'queue', role: 'Holds the work' },
      { to: '/patterns/gone.html', role: '' },
    ]);
  });

  it('prints the refs as text', async () => {
    expect((await kb(root, 'refs', 'breaker')).out).toBe(
      [
        '# Breaker  [breaker]\n',
        'relations (2)',
        '  combines-with: retry',
        '  prevents-hazard: storm',
        '\nfluency tie-ins (1)\n  steady',
        '\nprose links (3)\n  retry, storm, queue',
        '\nmermaid clicks (1)\n  retry',
        '\nuntyped — linked in prose, no typed relation (1)\n  queue',
      ].join('\n'),
    );
    // A sibling row is a typed carrier, not a prose link.
    expect((await kb(root, 'refs', 'loop')).out).toContain('\ntheme members (2)\n  queue [Holds the work], /patterns/gone.html\n\nprose links (0)\n\nmermaid clicks (0)\n');
  });

  it('finds the page by --file, from its markdown', async () => {
    const md = path.join(root, 'docs/hazards/storm.md');
    expect(JSON.parse((await kb(root, 'refs', '--file', md, '--json')).out)['id']).toBe('storm');
  });

  it('refuses a --file that is missing, outside docs/, or no page', async () => {
    expect((await kb(root, 'refs', '--file', path.join(root, 'docs/nope.md'))).err).toBe(`no such file: ${path.join(root, 'docs/nope.md')}`);
    sb.write('elsewhere.md', 'x');
    expect((await kb(root, 'refs', '--file', path.join(root, 'elsewhere.md'))).err).toBe(`not under docs/: ${path.join(root, 'elsewhere.md')}`);
    sb.write('docs/reference/unlisted.md', '# Unlisted\n');
    expect((await kb(root, 'refs', '--file', path.join(root, 'docs/reference/unlisted.md'))).err).toBe(
      'docs/reference/unlisted.md: no row in docs/data/site-structure.json lists this page',
    );
    sb.write('site/index.html', '<html></html>');
    expect((await kb(root, 'refs', '--file', path.join(root, 'site/index.html'))).err).toBe(`not under docs/: ${path.join(root, 'site/index.html')}`);
  });

  it('says a page the structure file lists in an area of no kind is not a knowledge-base page', async () => {
    const why = (rel: string): string =>
      `${rel}: the structure file lists it in area "reference", which holds no knowledge-base kind — kb.mjs reads the seven kinds only`;
    for (const cmd of ['validate', 'refs']) {
      expect(await kb(root, cmd, '--file', path.join(root, 'docs/reference/notes.md')), cmd).toEqual({ code: 1, out: '', err: why('docs/reference/notes.md') });
    }
    // The kind pages still answer, and the listing leaves the reference row out.
    expect((await kb(root, 'ls')).out.endsWith('\n10 entries.')).toBe(true);
  });
});

describe('validate', () => {
  it('lints every page and names each problem', async () => {
    const r = await kb(root, 'validate');
    expect(r.code).toBe(1);
    expect(r.err).toBe('2 problem(s) across 10 page(s):\n  queue: tags carries 1 tag(s); a page needs 2-5\n  queue: sketch code does not name its language');
  });

  it('lints one page, by id or by --file, and prints JSON', async () => {
    expect(await kb(root, 'validate', 'breaker')).toEqual({ code: 0, out: 'OK — 1 page(s) structurally valid.', err: '' });
    const r = await kb(root, 'validate', '--file', path.join(root, 'docs/patterns/messaging/queue.md'), '--json');
    expect(r.code).toBe(1);
    expect(JSON.parse(r.out)).toEqual({ pages: 1, problems: ['queue: tags carries 1 tag(s); a page needs 2-5', 'queue: sketch code does not name its language'] });
  });
});

describe('main', () => {
  it('runs only as the entry point, writing to the process', async () => {
    const file = path.join(path.dirname(fileURLToPath(import.meta.url)), 'cli.ts');
    const url = pathToFileURL(file).href;
    main(url, ['node', '/elsewhere.js']);
    main(url, ['node']);
    const broken = makeSandbox();
    writeKbFixture(broken.dir);
    broken.write('docs/data/content-model.json', '{"kinds":[]}');
    const writes: string[] = [];
    const said = (): string => writes.join('');
    const out = vi.spyOn(process.stdout, 'write').mockImplementation((s) => {
      writes.push(String(s));
      return true;
    });
    const err = vi.spyOn(process.stderr, 'write').mockImplementation((s) => {
      writes.push(String(s));
      return true;
    });
    const before = process.exitCode;
    const env = process.env['KB_ROOT'];
    try {
      process.env['KB_ROOT'] = root;
      main(url, ['node', file, 'validate', 'breaker']);
      await vi.waitFor(() => expect(said()).toContain('OK — 1 page(s)'));
      await vi.waitFor(() => expect(process.exitCode).toBe(0));
      main(url, ['node', file, 'get', 'break']);
      await vi.waitFor(() => expect(said()).toContain('unknown id: break\n'));
      await vi.waitFor(() => expect(process.exitCode).toBe(1));
      process.env['KB_ROOT'] = broken.dir;
      main(url, ['node', file, 'ls']);
      await vi.waitFor(() => expect(said()).toMatch(/kb\.mjs: .+/));
      await vi.waitFor(() => expect(process.exitCode).toBe(2));
    } finally {
      if (env === undefined) delete process.env['KB_ROOT'];
      else process.env['KB_ROOT'] = env;
      out.mockRestore();
      err.mockRestore();
      process.exitCode = before;
      broken.cleanup();
    }
  });

  it('stops quietly when the reader goes away, and throws any other stream error', () => {
    const stream = new PassThrough();
    quietOnClose(stream);
    const fail = (code: string): Error => Object.assign(new Error(code), { code });
    expect(() => stream.emit('error', fail('EPIPE'))).not.toThrow();
    expect(() => stream.emit('error', fail('EIO'))).toThrow('EIO');
  });

  it('shares one corpus across runs', async () => {
    const corpus = new Corpus(root);
    expect((await kb(corpus, 'get', 'retry', '--block', 'description')).out).toContain('Try again after a pause');
    expect((await kb(corpus, 'get', 'retry', '--block', 'description')).out).toContain('Try again after a pause');
  });
});
