/**
 * The data files a writer edits: read, refused while generated, printed back
 * in the layout they already have, dated on a real change only.
 */

import fs from 'node:fs';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { makeSandbox, type Sandbox } from '../lib/sandbox.js';

import { REPO } from './corpus.js';
import { dataBytes, layoutOf, ownerNote, printJson, printPlain, readData, today } from './data.js';

let sb: Sandbox;
beforeEach(() => {
  sb = makeSandbox();
});
afterEach(() => sb.cleanup());

describe('the two layouts', () => {
  it('prints a list of scalars and a row of scalars on one line, compact', () => {
    const v = { version: 1, areas: [{ id: 'a', pages: [{ slug: 'x', n: 1 }], tags: [] }], empty: {}, gone: undefined, list: ['a', 'b'] };
    expect(printJson(v)).toBe(
      '{\n  "version": 1,\n  "areas": [\n    {\n      "id": "a",\n      "pages": [\n        { "slug": "x", "n": 1 }\n      ],\n      "tags": []\n    }\n  ],\n  "empty": {},\n  "list": ["a", "b"]\n}\n',
    );
    expect(printPlain({ a: [1] })).toBe('{\n  "a": [\n    1\n  ]\n}\n');
  });

  it('holds printJson to the bytes the extraction writes the real structure file in', () => {
    const real = fs.readFileSync(path.join(REPO, 'docs/data/site-structure.json'), 'utf8');
    expect(printJson(JSON.parse(real))).toBe(real);
    expect(layoutOf(real)).toBe(printJson);
    const relations = fs.readFileSync(path.join(REPO, 'docs/data/relations.json'), 'utf8');
    expect(layoutOf(relations)).toBe(printPlain);
  });
});

describe('today', () => {
  it('is the local date, zero-padded', () => {
    expect(today(new Date(2026, 0, 5, 23, 59))).toBe('2026-01-05');
    expect(today()).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });
});

describe('readData', () => {
  it('refuses a file its note says a generator writes, as prerequisites.json says', () => {
    expect(ownerNote({ note: 'This file is GENERATED by x from y.' })).toBe(true);
    expect(ownerNote({ note: 'Hand-written.' })).toBe(false);
    expect(ownerNote({ note: 1 })).toBe(false);
    expect(() => readData(REPO, 'docs/data/prerequisites.json')).toThrow(/docs\/data\/prerequisites\.json is generated \(its note says so\): edit the file its note names, then run make gen/);
    expect(() => readData(REPO, 'docs/data/relations.json')).not.toThrow();
  });

  it('names a file it cannot read or parse', () => {
    expect(() => readData(sb.dir, 'docs/data/none.json')).toThrow(/^cannot read docs\/data\/none\.json: ENOENT/);
    sb.write('docs/data/bad.json', '{ nope');
    expect(() => readData(sb.dir, 'docs/data/bad.json')).toThrow(/^cannot read docs\/data\/bad\.json: /);
  });

  it('dates a real change, and leaves a no-op alone', () => {
    const bytes = printPlain({ version: 1, updated: '2026-01-01', note: 'Hand-written.', rows: [1] });
    sb.write('d.json', bytes);
    const f = readData<{ version: number; updated: string; note: string; rows: number[] }>(sb.dir, 'd.json');
    expect(f.print).toBe(printPlain);
    expect(dataBytes(f, f.value, '2026-09-28')).toBe(bytes);
    expect(dataBytes(f, { ...f.value, updated: '1999-01-01' }, '2026-09-28')).toBe(bytes);
    const changed = JSON.parse(dataBytes(f, { ...f.value, rows: [1, 2] }, '2026-09-28')) as Record<string, unknown>;
    expect(Object.keys(changed)).toEqual(['version', 'updated', 'note', 'rows']);
    expect(changed['updated']).toBe('2026-09-28');
  });
});
