/**
 * The data files kb.mjs v2's writers change — `relations.json`,
 * `learning-paths.json`, `site-structure.json` — read, edited and written
 * back in the layout they already have, with `updated` moved to the day of
 * the edit (spec kb.data.source-file: "date of the last edit").
 *
 * Two layouts are in use today, and a writer keeps whichever the file holds:
 *
 *   plain     `JSON.stringify(v, null, 2)` — relations.json, learning-paths.json
 *   compact   `printJson` — the extraction's layout, a list of scalars and an
 *             object of scalars inside a list on one line — site-structure.json
 *
 * A data file a generator writes says so in its `note` ("… GENERATED by …"):
 * `ownerNote` finds that, and the writers refuse such a file, so kb.mjs never
 * writes what `make gen` would overwrite.
 */

import fs from 'node:fs';
import path from 'node:path';

import { STAMP_PREFIX } from '../lib/generated.js';

import { KbError } from './corpus.js';

function isScalar(v: unknown): boolean {
  return v === null || typeof v !== 'object';
}

/**
 * JSON with two-space indentation and one-line forms where a person reads a
 * value as one thing: a list of scalars, and an object of scalars inside a
 * list. The layout the structure file is written in; data.test.ts holds it to
 * the same bytes on the real file.
 */
export function printJson(value: unknown): string {
  const fmt = (v: unknown, indent: string, inList: boolean): string => {
    if (isScalar(v)) return JSON.stringify(v);
    const inner = `${indent}  `;
    if (Array.isArray(v)) {
      if (v.length === 0) return '[]';
      if (v.every(isScalar)) return `[${v.map((x) => JSON.stringify(x)).join(', ')}]`;
      return `[\n${v.map((x) => inner + fmt(x, inner, true)).join(',\n')}\n${indent}]`;
    }
    const entries = Object.entries(v as Record<string, unknown>).filter(([, x]) => x !== undefined);
    if (entries.length === 0) return '{}';
    if (inList && entries.every(([, x]) => isScalar(x))) {
      return `{ ${entries.map(([k, x]) => `${JSON.stringify(k)}: ${JSON.stringify(x)}`).join(', ')} }`;
    }
    return `{\n${entries.map(([k, x]) => `${inner}${JSON.stringify(k)}: ${fmt(x, inner, false)}`).join(',\n')}\n${indent}}`;
  };
  return `${fmt(value, '', false)}\n`;
}

/** `JSON.stringify` with two spaces and a closing newline. */
export function printPlain(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/** The printer that reproduces `current` byte for byte: the compact layout when it does, else plain. */
export function layoutOf(current: string): (value: unknown) => string {
  return printJson(JSON.parse(current)) === current ? printJson : printPlain;
}

/** The day of an edit, `YYYY-MM-DD`, in local time. */
export function today(now: Date = new Date()): string {
  const pad = (n: number): string => String(n).padStart(2, '0');
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
}

/** Whether a data file's note says a generator writes it. */
export function ownerNote(value: Readonly<Record<string, unknown>>): boolean {
  const note = value['note'];
  return typeof note === 'string' && note.includes(`${STAMP_PREFIX} `);
}

/** A data file held for an edit: its bytes, its value, and how to print it back. */
export interface DataFile<T> {
  readonly rel: string;
  readonly current: string;
  readonly value: T;
  readonly print: (value: unknown) => string;
}

/** Read a data file for an edit, or refuse one its note says is generated. */
export function readData<T>(root: string, rel: string): DataFile<T> {
  let current: string;
  let value: Record<string, unknown>;
  try {
    current = fs.readFileSync(path.join(root, rel), 'utf8');
    value = JSON.parse(current) as Record<string, unknown>;
  } catch (e) {
    throw new KbError(`cannot read ${rel}: ${(e as Error).message}`);
  }
  if (ownerNote(value)) {
    throw new KbError(`${rel} is generated (its note says so): edit the file its note names, then run make gen`);
  }
  return { rel, current, value: value as T, print: layoutOf(current) };
}

/**
 * The file's new bytes: `value` with `updated` set to `day`, in the file's
 * own layout — or the old bytes untouched when nothing but the date would
 * change, so a no-op edit leaves the file alone.
 */
export function dataBytes<T extends object>(file: DataFile<T>, value: T, day: string): string {
  const same = file.print({ ...value, updated: (file.value as { updated?: unknown }).updated });
  if (same === file.current) return file.current;
  return file.print({ ...value, updated: day });
}
