/**
 * The page `kb.mjs new` writes, from its parts: every required block in
 * order, each with the placeholder its shape takes, and a page the dialect
 * reads back without a problem.
 */

import { describe, expect, it } from 'vitest';

import { printFrontmatter } from '../lib/frontmatter.js';

import { parsePage } from './page.js';
import { scaffoldText, TODO } from './scaffold.js';

const text = scaffoldText({
  frontmatter: printFrontmatter([
    ['title', 'A *new* page'],
    ['status', 'draft'],
  ]),
  title: 'A *new* page',
  blocks: ['description', 'explain', 'tradeoffs', 'sketch', 'tour', 'relationships'],
  heading: (b) => `Heading of ${b}`,
  groups: { tradeoffs: { fact: 'polarity', values: ['pro', 'con'] } },
  groupHeading: (b, v) => `${b} ${v}`,
  sketchLang: 'typescript',
  generated: (name) => [`<!-- GENERATED by gen-${name} from docs/data/x.json. Do not edit this block. -->`],
});

describe('scaffoldText for a kind that asks for costs', () => {
  it('writes two TODO costs bullets between the TODO paragraph and the example', () => {
    const withCosts = scaffoldText({
      frontmatter: printFrontmatter([['title', 'P']]),
      title: 'P',
      blocks: ['explain'],
      heading: (b) => b,
      groups: {},
      groupHeading: (b) => b,
      sketchLang: 'typescript',
      costs: true,
      generated: () => [],
    });
    expect(withCosts).toContain('<!--meta block=explain-->\n\nTODO.\n\n- **TODO.** TODO.\n- **TODO.** TODO.\n\n**Example.** TODO.');
  });
});

describe('scaffoldText', () => {
  it('writes the frontmatter, the title, a lead and each block in the order given', () => {
    expect(text).toBe(
      [
        '---',
        'title: A *new* page',
        'status: draft',
        '---',
        '',
        '# A \\*new\\* page',
        '',
        'TODO — the longer definition sentence.',
        '',
        '## Heading of description',
        '<!--meta block=description-->',
        '',
        TODO,
        '',
        '## Heading of explain',
        '<!--meta block=explain-->',
        '',
        'TODO.',
        '',
        '**Example.** TODO.',
        '',
        '## Heading of tradeoffs',
        '<!--meta block=tradeoffs-->',
        '',
        '### tradeoffs pro',
        '<!--meta polarity=pro-->',
        '',
        '- TODO.',
        '',
        '### tradeoffs con',
        '<!--meta polarity=con-->',
        '',
        '- TODO.',
        '',
        '## Heading of sketch',
        '<!--meta block=sketch-->',
        '',
        '```typescript summary="TODO — what the sketch shows"',
        '// TODO',
        '```',
        '',
        '## Heading of tour',
        '<!--meta block=tour-->',
        '',
        'TODO — the stages, as the profile in docs/data/learning-paths.json lists them.',
        '',
        '<!-- tour:start -->',
        '',
        '<!-- GENERATED by gen-tour from docs/data/x.json. Do not edit this block. -->',
        '',
        '<!-- tour:end -->',
        '',
        '## Heading of relationships',
        '<!--meta block=relationships-->',
        '',
        '<!-- relationships:start -->',
        '',
        '<!-- GENERATED by gen-relationships from docs/data/x.json. Do not edit this block. -->',
        '',
        '<!-- relationships:end -->',
        '',
      ].join('\n'),
    );
  });

  it('reads back through the dialect with no problem, block by block', () => {
    const doc = parsePage(text);
    expect(doc.problems).toEqual([]);
    expect(doc.h1).toBe('A *new* page');
    expect(doc.blocks.map((b) => b.name)).toEqual(['description', 'explain', 'tradeoffs', 'sketch', 'tour', 'relationships']);
    expect([...new Set(doc.regionOf.values())]).toEqual(['tour', 'relationships']);
  });
});
