/**
 * `emit()` is the half of every generator that decides whether to write or to
 * complain, and `splice()` is how a generator owns part of a page a person
 * wrote. Written once per generator, those halves disagree; written here, they
 * cannot. The property the whole file defends: a `--check` run never writes.
 */

import fs from 'node:fs';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  BLOCK_NAME,
  blockStamp,
  emit,
  fileStamp,
  isStamped,
  markers,
  splice,
  spliceFile,
  STAMP_PREFIX,
  type EmitOptions,
} from './generated.js';
import type { GateSpec } from './gate.js';
import {
  expectFail,
  expectMisuse,
  expectPass,
  makeSandbox,
  type Captured,
  type Sandbox,
} from './sandbox.js';

const OUT = 'docs/generated.md';
const STAMP = fileStamp('tools/src/gen/demo.ts', 'docs/data/demo.json');
const WANTED = `# Generated\n\n${STAMP}\n\nline one\nline two\n`;

const options = (over: Partial<EmitOptions> = {}): EmitOptions => ({
  out: OUT,
  wanted: WANTED,
  fixCommand: 'make generated',
  stamp: STAMP,
  ...over,
});

/** A gate whose whole body is one emit() call — the shape every generator has. */
const generator = (over: Partial<EmitOptions> = {}): GateSpec => ({
  name: 'demo',
  usage: 'usage: demo [--check]',
  flags: ['--check'],
  run: (ctx) => {
    const what = emit(ctx, options(over));
    return what === 'fresh' ? '[demo] the page is in sync' : `[demo] ${what} the page`;
  },
});

let sb: Sandbox;
beforeEach(() => {
  sb = makeSandbox();
});
afterEach(() => sb.cleanup());

const tempDirs = (): string[] => fs.readdirSync(sb.dir).filter((n) => n.startsWith('.gen-check-'));

// ---------------------------------------------------------------------------
// Stamps
// ---------------------------------------------------------------------------
describe('stamps', () => {
  it('open with the two words one search finds them all by', () => {
    // output-ownership-C2: a file stamp and every block stamp share a prefix.
    expect(STAMP).toContain(`<!-- ${STAMP_PREFIX} tools/src/gen/demo.ts from docs/data/demo.json.`);
    expect(STAMP.endsWith('Do not edit this file. -->')).toBe(true);
    for (const shape of ['table', 'paragraph', 'block'] as const) {
      const s = blockStamp('g.ts', 'd.json', shape);
      expect(s.startsWith(`<!-- ${STAMP_PREFIX} g.ts from d.json.`)).toBe(true);
      expect(s.endsWith(`Do not edit this ${shape}. -->`)).toBe(true);
    }
  });

  it('count a file as stamped only by a whole-file stamp on a line of its own, outside a fence, anywhere in it', () => {
    const body = 'GENERATED by tools/src/gen/x.ts from docs/data/x.json. Do not edit this file.';
    // Every comment syntax a generated file uses, and one below frontmatter.
    for (const line of [`<!-- ${body} -->`, `// ${body}`, `# ${body}`, `/* ${body} */`, `{/* ${body} */}`, `  <!-- ${body} -->  `]) {
      expect(isStamped(`---\ntitle: x\n---\n\n${line}\n\n# X\n`), line).toBe(true);
    }
    expect(isStamped(STAMP)).toBe(true);
    // A page that only mentions or quotes a stamp is hand-written.
    expect(isStamped('The hub is GENERATED by a script; this page is not.\n')).toBe(false);
    expect(isStamped(`A generated page opens with \`${STAMP}\`; this one is hand-written.\n`)).toBe(false);
    expect(isStamped(`\`\`\`markdown\n${STAMP}\n\`\`\`\n`)).toBe(false);
    expect(isStamped(`~~~\n${STAMP}\n~~~\n`)).toBe(false);
    // A block stamp owns its block, not the file.
    expect(isStamped(blockStamp('g.ts', 'd.json', 'table'))).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------
describe('the write branch', () => {
  it('writes the file and says so', async () => {
    const r = await sb.run(generator());
    expectPass(r);
    expect(r.out).toBe('[demo] wrote the page');
    expect(sb.read(OUT)).toBe(WANTED);
  });

  it('creates the directory the file goes in', async () => {
    expect(sb.exists('docs')).toBe(false);
    await sb.run(generator({ out: 'a/deeply/nested/page.md' }));
    expect(sb.read('a/deeply/nested/page.md')).toBe(WANTED);
  });

  it('overwrites its own stale output rather than appending to it', async () => {
    sb.write(OUT, `${STAMP}\nsomething a person typed here\n`);
    await sb.run(generator());
    expect(sb.read(OUT)).toBe(WANTED);
  });

  it('finds its stamp anywhere in the file, not only on the first line', async () => {
    // output-ownership-C4: frontmatter sits above the stamp on a real page.
    sb.write(OUT, `---\ntitle: x\n---\n\n${'filler\n'.repeat(60)}${STAMP}\n`);
    expectPass(await sb.run(generator()));
    expect(sb.read(OUT)).toBe(WANTED);
  });

  it('never overwrites a hand-written file at its path: one note, exit 0', async () => {
    // output-ownership-C3: a generator writes a path only when nothing is
    // there or the file carries its own stamp.
    sb.write(OUT, '# Written by a person\n');
    const r = await sb.run(generator());
    expectPass(r);
    expect(r.err).toBe(`[demo] skipped ${OUT}: it does not carry this generator's stamp, so it is not ours to write`);
    expect(sb.read(OUT)).toBe('# Written by a person\n');
  });

  it('is byte-for-byte stable when run twice', async () => {
    await sb.run(generator());
    const first = sb.read(OUT);
    await sb.run(generator());
    expect(sb.read(OUT)).toBe(first);
  });

  it('leaves a file that already holds the wanted bytes untouched, and says it is in sync', async () => {
    // Another session's --check may be reading it; and "wrote" counts real changes only.
    sb.write(OUT, WANTED);
    const abs = path.join(sb.dir, OUT);
    fs.utimesSync(abs, 1000, 1000);
    const r = await sb.run(generator());
    expectPass(r);
    expect(r.out).toBe('[demo] the page is in sync');
    expect(fs.statSync(abs).mtimeMs).toBe(1_000_000);
  });

  it('writes through a temp file and a rename, and leaves no temp file behind', async () => {
    sb.write(OUT, `${STAMP}\nstale\n`);
    const ino = fs.statSync(path.join(sb.dir, OUT)).ino;
    expectPass(await sb.run(generator()));
    expect(sb.read(OUT)).toBe(WANTED);
    // A rename puts a new file in place; an in-place write keeps the old inode.
    expect(fs.statSync(path.join(sb.dir, OUT)).ino).not.toBe(ino);
    expect(fs.readdirSync(path.join(sb.dir, 'docs'))).toEqual(['generated.md']);
  });

  it('cleans its temp file up when the write fails, and the failure still surfaces', async () => {
    fs.mkdirSync(path.join(sb.dir, 'locked'));
    fs.chmodSync(path.join(sb.dir, 'locked'), 0o555);
    try {
      await expect(sb.run(generator({ out: 'locked/page.md' }))).rejects.toThrow(/EACCES/);
      expect(fs.readdirSync(path.join(sb.dir, 'locked'))).toEqual([]);
    } finally {
      fs.chmodSync(path.join(sb.dir, 'locked'), 0o755);
    }
  });
});

// ---------------------------------------------------------------------------
// Checking
// ---------------------------------------------------------------------------
describe('--check', () => {
  it('passes an up-to-date file with one summary line and nothing on stderr', async () => {
    sb.write(OUT, WANTED);
    const r = await sb.run(generator(), ['--check']);
    expectPass(r);
    expect(r.out).toBe('[demo] the page is in sync');
    expect(r.err).toBe('');
  });

  it('fails a stale file, names it stale, and names the fix', async () => {
    sb.write(OUT, `${WANTED}hand-edited\n`);
    const r = await sb.run(generator(), ['--check']);
    expectFail(r);
    expect(r.err).toContain(`${OUT} is STALE — run: make generated`);
  });

  it('prints a diff, oriented so `>` is what the file has now', async () => {
    // The wanted text goes first, so a `>` line is the surprise and a `<` line
    // is the intent.
    sb.write(OUT, WANTED.replace('line two', 'something else'));
    const r = await sb.run(generator(), ['--check']);
    expect(r.err).toContain('< line two');
    expect(r.err).toContain('> something else');
  });

  it('fails a file that does not exist at all, with the whole render as the diff', async () => {
    const r = await sb.run(generator(), ['--check']);
    expectFail(r);
    expect(r.err).toContain('is STALE');
    expect(r.err).toContain('< line one');
    expect(sb.exists(OUT)).toBe(false);
  });

  it('writes nothing — not the file, and not a leftover temp dir', async () => {
    sb.write(OUT, 'stale\n');
    await sb.run(generator(), ['--check']);
    expect(sb.read(OUT)).toBe('stale\n');
    expect(tempDirs()).toEqual([]);
  });

  it('cleans the temp dir up even when the file is missing', async () => {
    await sb.run(generator(), ['--check']);
    expect(tempDirs()).toEqual([]);
  });

  it('names the repair that clears a file without its stamp, since `make generated` skips it', async () => {
    sb.write(OUT, '# Written by a person\n');
    const r = await sb.run(generator(), ['--check']);
    expectFail(r, `${OUT} does not carry this generator's stamp, so a write never replaces it — move it out or delete it, then run: make generated`);
    expect(r.err).not.toContain('STALE');
  });
});

// ---------------------------------------------------------------------------
// The contract emit() inherits
// ---------------------------------------------------------------------------
describe('under the gate contract', () => {
  it('swallows the summary when it reported staleness', async () => {
    sb.write(OUT, 'stale\n');
    const r = await sb.run(generator(), ['--check']);
    expect(r.out).toBe('');
  });

  it('does not write when argv is wrong — argv is validated first', async () => {
    const misspelt: Captured = await sb.run(generator(), ['--chekc']);
    expectMisuse(misspelt);
    const extra: Captured = await sb.run(generator(), ['--check', 'extra']);
    expectMisuse(extra);
    expect(sb.exists(OUT)).toBe(false);
  });

  it('treats an absent --check as the write branch', async () => {
    sb.write(OUT, `${STAMP}\nstale\n`);
    await sb.run(generator(), []);
    expect(sb.read(OUT)).toBe(WANTED);
  });
});

describe('byte-exactness', () => {
  it('does not add or remove a trailing newline', async () => {
    // A generator's wanted text ends how it ends; emit is not allowed an
    // opinion, or every --check disagrees with every write by one byte.
    for (const wanted of ['no trailing newline', 'one\n', 'two\n\n']) {
      const s = makeSandbox();
      try {
        const bare: GateSpec = {
          ...generator(),
          run: (ctx) => `[demo] ${emit(ctx, { out: OUT, wanted, fixCommand: 'x' })}`,
        };
        await s.run(bare);
        expect(fs.readFileSync(path.join(s.dir, OUT), 'utf8')).toBe(wanted);
        expectPass(await s.run(bare, ['--check']));
      } finally {
        s.cleanup();
      }
    }
  });
});

describe('write-or-check-O2', () => {
  it('write-or-check-O2: a hand-appended line is STALE with the real path and command, then repaired', async () => {
    // A sandbox's freshly written output…
    expectPass(await sb.run(generator()));
    expectPass(await sb.run(generator(), ['--check']));
    // …gains one hand-appended line.
    sb.write(OUT, `${sb.read(OUT)}a line someone added\n`);
    const before = sb.snapshot();

    const r = await sb.run(generator(), ['--check']);
    expectFail(r);
    const err = r.err.split('\n');
    expect(err[0]).toBe(`[demo] FAIL: ${OUT} is STALE — run: make generated`);
    // Then diff lines, rendered text first: the appended line is on the `>` side.
    expect(err.slice(1)).toContain('> a line someone added');
    // No summary line, no temporary file, no byte changed.
    expect(r.out).toBe('');
    expect(tempDirs()).toEqual([]);
    expect(sb.snapshot()).toEqual(before);

    // After the repair command (the generator, unflagged), --check exits 0.
    expectPass(await sb.run(generator()));
    expectPass(await sb.run(generator(), ['--check']));
  });
});

// ---------------------------------------------------------------------------
// Marked blocks
// ---------------------------------------------------------------------------
const PAGE = [
  '# A hand-written page',
  '',
  'Prose before.',
  '',
  '<!-- counts:start -->',
  'a stale line',
  '<!-- counts:end -->',
  '',
  'Prose between.',
  '',
  '<!-- table:start -->',
  '<!-- table:end -->',
  '',
  'Prose after.',
  '',
].join('\n');

const COUNTS = { name: 'counts', lines: [blockStamp('g.ts', 'd.json', 'paragraph'), '', 'There are 3.'] };
const TABLE = { name: 'table', lines: [blockStamp('g.ts', 'd.json', 'table'), '', '| a |', '| --- |', '| 1 |'] };

describe('markers', () => {
  it('pairs a start and an end marker under one name', () => {
    expect(markers('gate-count')).toEqual(['<!-- gate-count:start -->', '<!-- gate-count:end -->']);
  });

  it('takes only lower-case letters and hyphens as a name', () => {
    expect(BLOCK_NAME.test('gates-symptoms')).toBe(true);
    expect(BLOCK_NAME.test('Gates')).toBe(false);
    expect(() => markers('bad_name')).toThrow(/lower-case/);
  });
});

describe('splice', () => {
  it('replaces each inside and leaves every byte outside the markers alone', () => {
    const r = splice(PAGE, [COUNTS, TABLE]);
    if (!('text' in r)) throw new Error('expected a splice');
    const [open] = markers('counts');
    const [, close] = markers('table');
    // marked-blocks-C3: before the first start marker and from the last end
    // marker on, the bytes are the page's own.
    expect(r.text.slice(0, r.text.indexOf(open))).toBe(PAGE.slice(0, PAGE.indexOf(open)));
    expect(r.text.slice(r.text.indexOf(close))).toBe(PAGE.slice(PAGE.indexOf(close)));
    expect(r.text).not.toContain('a stale line');
    expect(r.text).toContain('Prose between.');
    // The table sits whole inside its block, header row included (C7).
    expect(r.text).toContain('<!-- table:start -->\n\n<!-- GENERATED by g.ts from d.json. Do not edit this table. -->\n\n| a |\n| --- |\n| 1 |\n\n<!-- table:end -->');
  });

  it('is stable: splicing its own output changes nothing', () => {
    const once = splice(PAGE, [COUNTS, TABLE]);
    if (!('text' in once)) throw new Error('expected a splice');
    const twice = splice(once.text, [COUNTS, TABLE]);
    expect(twice).toEqual(once);
  });

  it('names every missing marker, not only the first', () => {
    const broken = PAGE.replace('<!-- counts:end -->', '').replace('<!-- table:start -->', '');
    expect(splice(broken, [COUNTS, TABLE])).toEqual({
      missing: ['<!-- counts:end -->', '<!-- table:start -->'],
    });
  });

  it('does not take an end marker that comes before its start marker', () => {
    const backwards = '<!-- x:end -->\n<!-- x:start -->\n';
    expect(splice(backwards, [{ name: 'x', lines: [] }])).toEqual({ missing: ['<!-- x:end -->'] });
  });
});

describe('spliceFile', () => {
  const spec = (file: string): GateSpec => ({
    name: 'demo',
    usage: 'usage: demo [--check]',
    flags: ['--check'],
    run: (ctx) => {
      const text = spliceFile(ctx, file, [COUNTS, TABLE]);
      if (text === null) return '';
      const what = emit(ctx, { out: file, wanted: text, fixCommand: 'make generated' });
      return `[demo] ${what} ${file}`;
    },
  });

  it('writes the blocks, then --check agrees', async () => {
    sb.write('docs/page.md', PAGE);
    expectPass(await sb.run(spec('docs/page.md')));
    expect(sb.read('docs/page.md')).toContain('There are 3.');
    expectPass(await sb.run(spec('docs/page.md'), ['--check']));
  });

  it('calls an edit inside a block drift, and an edit outside it none', async () => {
    // marked-blocks-C4.
    sb.write('docs/page.md', PAGE);
    await sb.run(spec('docs/page.md'));
    const fresh = sb.read('docs/page.md');
    sb.write('docs/page.md', fresh.replace('Prose between.', 'Prose between, reworded.'));
    expectPass(await sb.run(spec('docs/page.md'), ['--check']));
    sb.write('docs/page.md', fresh.replace('There are 3.', 'There are 4.'));
    const r = await sb.run(spec('docs/page.md'), ['--check']);
    expectFail(r, 'docs/page.md is STALE — run: make generated');
  });

  it('names the file and the missing marker, and leaves the file as it was', async () => {
    // marked-blocks-C5.
    const broken = PAGE.replace('<!-- table:start -->\n', '');
    sb.write('docs/page.md', broken);
    const r = await sb.run(spec('docs/page.md'));
    expectFail(r);
    expect(r.err).toBe('[demo] FAIL docs/page.md: lacks the <!-- table:start --> marker');
    expect(sb.read('docs/page.md')).toBe(broken);
  });

  it('names a missing file, and does not create it', async () => {
    const r = await sb.run(spec('docs/gone.md'));
    expectFail(r, '[demo] FAIL docs/gone.md: is missing');
    expect(sb.exists('docs/gone.md')).toBe(false);
  });
});
