/**
 * The write-or-check half of every generator, and the marked blocks it splices
 * into hand-written pages (spec: kb.generation.write-or-check,
 * kb.generation.output-ownership, kb.generation.marked-blocks).
 *
 * Every generated file in this repo is committed and has a `--check` mode that
 * CI runs, so the two halves have to agree byte for byte. Doing that once here
 * is what stops a generator from writing one thing and checking another. A
 * mistyped `--chekc` falling through to the write branch and silently
 * regenerating a page is the reason the contract validates argv before
 * `run()` starts.
 */

import fs from 'node:fs';
import path from 'node:path';

import { run } from './exec.js';
import type { GateContext } from './gate.js';

// ---------------------------------------------------------------------------
// Stamps
// ---------------------------------------------------------------------------

/**
 * The two words every stamp opens with, in any comment syntax, so one
 * fixed-text search lists every generated file (output-ownership-C2).
 */
export const STAMP_PREFIX = 'GENERATED by';

/** The stamp a whole generated page carries as its first body line. */
export function fileStamp(generator: string, source: string): string {
  return `<!-- ${STAMP_PREFIX} ${generator} from ${source}. Do not edit this file. -->`;
}

/**
 * A whole-file stamp as a line of its own, in any comment syntax a generated
 * file uses: HTML, `//`, `#`, `/* … *\/`, or MDX's `{/* … *\/}`.
 */
export const FILE_STAMP = new RegExp(
  `^\\s*(?:<!--|//|#|\\{?/\\*)\\s*${STAMP_PREFIX} \\S+ from \\S+\\. Do not edit this file\\.\\s*(?:-->|\\*/\\}?)?\\s*$`,
);

/**
 * A file stamped whole by a generator: some line of its own, outside a fence,
 * is a whole-file stamp. The whole file is searched, so a stamp below
 * frontmatter counts (output-ownership-C4), and a page that quotes the stamp
 * in prose or in a sample is still hand-written. A marked block's stamp says
 * "this table" or "this block", never "this file", so a hand-written page
 * holding a generated block is not stamped whole.
 */
export function isStamped(text: string): boolean {
  let fenced = false;
  for (const line of text.split('\n')) {
    if (/^\s*(?:```|~~~)/.test(line)) fenced = !fenced;
    else if (!fenced && FILE_STAMP.test(line)) return true;
  }
  return false;
}

/** What a block stamp closes by naming: the shape of what it owns. */
export type BlockShape = 'table' | 'paragraph' | 'block';

/** The first line inside a marked block (marked-blocks-C2). */
export function blockStamp(generator: string, source: string, shape: BlockShape): string {
  return `<!-- ${STAMP_PREFIX} ${generator} from ${source}. Do not edit this ${shape}. -->`;
}

// ---------------------------------------------------------------------------
// Write or check
// ---------------------------------------------------------------------------

export interface EmitOptions {
  /** Repo-relative path of the generated file. */
  readonly out: string;
  /** What the file should contain, exactly — trailing newline included. */
  readonly wanted: string;
  /** The command a person runs to fix a stale file. */
  readonly fixCommand: string;
  /**
   * For a whole generated page: the stamp this generator writes. A file at
   * `out` that exists without it is hand-written, and a write skips it with a
   * note rather than overwrite it (output-ownership-C3). Omitted for a
   * hand-written page whose marked blocks were spliced into `wanted`.
   */
  readonly stamp?: string;
}

/** What one `emit` call did, for the generator's one summary line. */
export type Emitted = 'wrote' | 'fresh' | 'stale' | 'skipped';

/**
 * `--check`: compare and report. Otherwise: write. Returns what happened.
 *
 * Both branches read the same `wanted` bytes, rendered once by the caller
 * (write-or-check-C1). The diff is produced by `diff(1)` rather than
 * reimplemented — a hand-rolled one would be a second thing to trust.
 */
export function emit(ctx: GateContext, opts: EmitOptions): Emitted {
  const abs = path.join(ctx.root, opts.out);
  const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  // The whole file is searched for the stamp, never only its first lines
  // (output-ownership-C4): a stamp below frontmatter is still a stamp.
  const foreign = current !== null && opts.stamp !== undefined && !current.includes(opts.stamp);

  if (ctx.flags.has('--check')) {
    if (current === opts.wanted) return 'fresh';
    if (foreign) {
      // A write skips this file, so the fix command alone would never clear it.
      ctx.failLine(`${opts.out} does not carry this generator's stamp, so a write never replaces it — move it out or delete it, then run: ${opts.fixCommand}`);
      return 'stale';
    }
    ctx.failLine(`${opts.out} is STALE — run: ${opts.fixCommand}`);
    for (const line of diffLines(ctx.root, opts.out, opts.wanted)) ctx.failRaw(line);
    return 'stale';
  }

  if (foreign) {
    ctx.note(`skipped ${opts.out}: it does not carry this generator's stamp, so it is not ours to write`);
    return 'skipped';
  }
  // Bytes that already match are left alone: a reader in another session never
  // meets a rewrite nothing needed, and the summary counts real changes only.
  if (current === opts.wanted) return 'fresh';
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  writeAtomic(abs, opts.wanted);
  return 'wrote';
}

/**
 * Write through a sibling temp file and a rename, as scripts/lib/atomic.mjs
 * does: rename(2) is atomic within a filesystem, so a `--check` another
 * session runs meanwhile reads the old file or the new one, never a prefix.
 * The pid in the temp name keeps two writers off each other's temp file.
 */
function writeAtomic(file: string, data: string): void {
  const tmp = `${file}.tmp.${process.pid}`;
  try {
    fs.writeFileSync(tmp, data);
    fs.renameSync(tmp, file);
  } catch (e) {
    // No debris: a stray temp file beside a generated one reads as output.
    fs.rmSync(tmp, { force: true });
    throw e;
  }
}

function diffLines(root: string, out: string, wanted: string): string[] {
  const tmp = path.join(fs.mkdtempSync(path.join(root, '.gen-check-')), 'wanted');
  try {
    fs.writeFileSync(tmp, wanted);
    // `wanted` first, then the file on disk, so a `>` line means "what the
    // file has now". A missing file diffs against /dev/null.
    const target = path.join(root, out);
    const r = run('diff', [tmp, fs.existsSync(target) ? target : '/dev/null'], root);
    return r.stdout.split('\n').filter((l) => l !== '');
  } finally {
    fs.rmSync(path.dirname(tmp), { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// Marked blocks
// ---------------------------------------------------------------------------

/** A marker name: lower-case letters and hyphens (marked-blocks-C1). */
export const BLOCK_NAME = /^[a-z]+(?:-[a-z]+)*$/;

/** The start and end marker of one named block. */
export function markers(name: string): [string, string] {
  if (!BLOCK_NAME.test(name)) throw new Error(`block name "${name}" is not lower-case letters and hyphens`);
  return [`<!-- ${name}:start -->`, `<!-- ${name}:end -->`];
}

/** One block to fill: its marker name and the lines that go inside it. */
export interface Block {
  readonly name: string;
  readonly lines: readonly string[];
}

/**
 * The text with each block's inside replaced, or every marker it lacks.
 *
 * Bytes before a start marker and from its end marker on are untouched
 * (marked-blocks-C3). Every missing marker is named, not only the first, so a
 * file that lost two markers costs one run to repair.
 */
export function splice(text: string, blocks: readonly Block[]): { text: string } | { missing: string[] } {
  const missing: string[] = [];
  let out = text;
  for (const block of blocks) {
    const [open, close] = markers(block.name);
    const start = out.indexOf(open);
    const end = start === -1 ? out.indexOf(close) : out.indexOf(close, start + open.length);
    if (start === -1) missing.push(open);
    if (end === -1) missing.push(close);
    if (start === -1 || end === -1) continue;
    out = `${out.slice(0, start + open.length)}\n\n${block.lines.join('\n')}\n\n${out.slice(end)}`;
  }
  return missing.length > 0 ? { missing } : { text: out };
}

/**
 * Read a hand-written file and splice its blocks, or record why not.
 *
 * A missing file or marker is a finding naming the file and the missing part,
 * and the file is neither written nor created (marked-blocks-C5): returning
 * `null` is what keeps the caller from handing half a page to `emit`.
 */
export function spliceFile(ctx: GateContext, file: string, blocks: readonly Block[]): string | null {
  const abs = path.join(ctx.root, file);
  if (!fs.existsSync(abs)) {
    ctx.fail(file, 'is missing — it declares generated blocks, so create it with their markers');
    return null;
  }
  const result = splice(fs.readFileSync(abs, 'utf8'), blocks);
  if ('missing' in result) {
    for (const marker of result.missing) ctx.fail(file, `lacks the ${marker} marker`);
    return null;
  }
  return result.text;
}
