/**
 * The tour and fluency blocks: one membership stored once, rendered on both
 * pages, with the ids today's pages carry.
 */

import { describe, expect, it } from 'vitest';

import { deriveElements, parseKb } from './kb-attrs.js';
import type { PageRef } from './render-relations.js';
import {
  FLUENCY_BLOCK,
  GENERATOR,
  LEARNING_PATHS_SRC,
  renderFluency,
  renderTour,
  themesOf,
  TOUR_BLOCK,
  type LearningPaths,
} from './render-tours.js';

const ref = (slug: string, route: string, title: string): PageRef => ({
  slug,
  route,
  source: `docs${route.replace(/\.html$/, '.md')}`,
  title,
});
const CB = '/patterns/distributed/resilience/circuit-breaker.html';
const BH = '/patterns/distributed/resilience/bulkhead.html';
const RES = '/themes/resilience.html';
const OBS = '/themes/observability.html';
const PAGES = new Map<string, PageRef>(
  [
    ref('circuit-breaker', CB, 'Circuit Breaker'),
    ref('bulkhead', BH, 'Bulkhead'),
    ref('resilience', RES, 'Resilience'),
    ref('observability', OBS, 'Observability & *Tracing*'),
  ].map((p) => [p.route, p]),
);

const LP: LearningPaths = {
  version: 1,
  updated: '2026-09-23',
  note: 'n',
  profiles: [
    { id: 'resilience', label: 'Resilience', stages: [CB, BH] },
    { id: 'observability', label: 'Observability', stages: [CB] },
  ],
  notes: {
    [CB]: {
      resilience: { role: 'Stop calling', tour: 'Trips on failures — see [Bulkhead](../patterns/distributed/resilience/bulkhead.md).', fluency: 'Degrade gracefully.' },
      observability: { role: 'State', tour: 'Breaker state is a signal.', fluency: '' },
    },
    [BH]: {
      resilience: { role: 'Isolate', tour: 'Separate pools {one per dependency}', fluency: 'Pools.' },
    },
  },
};

const ctx = { pages: PAGES };
const stamp = `<!-- GENERATED by ${GENERATOR} from ${LEARNING_PATHS_SRC}. Do not edit this block. -->`;

describe('renderTour', () => {
  it('writes one heading and one paragraph per stage, in stage order', () => {
    expect(renderTour('resilience', LP, ctx)).toEqual([
      stamp,
      '',
      '### [Circuit Breaker](../patterns/distributed/resilience/circuit-breaker.md) {#tour-circuit-breaker}',
      '',
      'Trips on failures — see [Bulkhead](../patterns/distributed/resilience/bulkhead.md).',
      '',
      '### [Bulkhead](../patterns/distributed/resilience/bulkhead.md) {#tour-bulkhead}',
      '',
      'Separate pools \\{one per dependency}',
    ]);
    expect(TOUR_BLOCK).toBe('tour');
  });

  it('parses back with the ids it wrote', () => {
    const lines = renderTour('observability', LP, ctx);
    const els = deriveElements(parseKb(['## Tour', '<!--meta block=tour-->', '', ...lines].join('\n')).tree);
    expect(els.filter((e) => e.kind !== 'heading' || e.depth === 3).map((e) => [e.kind, e.id])).toEqual([
      ['heading', 'tour-circuit-breaker'],
      ['paragraph', 'tour-p-1'],
    ]);
  });

  it('refuses a theme with no profile, or a stage that is no page', () => {
    expect(() => renderTour('ghost', LP, ctx)).toThrow(/no profile/);
    const bad: LearningPaths = { ...LP, profiles: [{ id: 'resilience', label: 'x', stages: ['/nowhere.html'] }] };
    expect(() => renderTour('resilience', bad, ctx)).toThrow(/nowhere/);
  });

  it('omits the paragraph of a stage with no tour text', () => {
    const lp: LearningPaths = { ...LP, notes: {} };
    expect(renderTour('observability', lp, ctx)).toEqual([
      stamp,
      '',
      '### [Circuit Breaker](../patterns/distributed/resilience/circuit-breaker.md) {#tour-circuit-breaker}',
    ]);
  });
});

describe('renderFluency', () => {
  it('lists every theme touring the page, in the order of its notes, with its id', () => {
    expect(themesOf(CB, LP).map((p) => p.id)).toEqual(['resilience', 'observability']);
    // The page's own order wins over profile order; a touring theme with no note goes last.
    const flipped: LearningPaths = { ...LP, notes: { ...LP.notes, [CB]: { observability: LP.notes[CB]!['observability']! } } };
    expect(themesOf(CB, flipped).map((p) => p.id)).toEqual(['observability', 'resilience']);
    expect(renderFluency(CB, LP, ctx)).toEqual([
      stamp,
      '',
      '- [Resilience](../../../themes/resilience.md) — Degrade gracefully. {#fluency-resilience}',
      '- [Observability & \\*Tracing\\*](../../../themes/observability.md) {#fluency-observability}',
    ]);
    expect(FLUENCY_BLOCK).toBe('fluency');
  });

  it('parses back with the ids it wrote', () => {
    const lines = renderFluency(CB, LP, ctx);
    const { tree, problems } = parseKb(['## Where', '<!--meta block=fluency-->', '', ...lines].join('\n'));
    expect(problems).toEqual([]);
    const items = deriveElements(tree).filter((e) => e.kind === 'item');
    expect(items.map((e) => [e.id, e.text])).toEqual([
      ['fluency-resilience', 'Resilience — Degrade gracefully.'],
      ['fluency-observability', 'Observability & *Tracing*'],
    ]);
  });

  it('keeps profile order among touring themes the page has no note for', () => {
    const lp: LearningPaths = { ...LP, notes: {}, profiles: [{ id: 'observability', label: 'O', stages: [CB] }, { id: 'resilience', label: 'R', stages: [CB] }] };
    expect(themesOf(CB, lp).map((p) => p.id)).toEqual(['observability', 'resilience']);
  });

  it('refuses a profile whose theme is no page', () => {
    const lp: LearningPaths = { ...LP, profiles: [...LP.profiles, { id: 'ghost', label: 'Ghost', stages: [CB] }] };
    expect(() => renderFluency(CB, lp, ctx)).toThrow('learning paths: no page "ghost"');
  });

  it('is only the stamp on a page no theme tours', () => {
    expect(renderFluency(RES, LP, ctx)).toEqual([stamp]);
    expect(() => renderFluency('/nowhere.html', LP, ctx)).toThrow(/no page/);
  });
});
