/**
 * The relationships block: one record per edge read from both ends, groups in
 * a fixed order, and a block that parses back as the dialect says.
 */

import { describe, expect, it } from 'vitest';

import { parseKb, plainText } from './kb-attrs.js';
import {
  BLOCK,
  GENERATOR,
  groupOrderToRecord,
  inverseOf,
  labelOf,
  relationGroups,
  RELATIONS_SRC,
  renderRelations,
  sidesOf,
  type PageRef,
  type RelationsFile,
  type Verbs,
} from './render-relations.js';

const VERBS: Verbs = {
  'combines-with': { label: 'Combines with', symmetric: true },
  prerequisite: { label: 'Requires', inverse: 'enables' },
  enables: { label: 'Enables', inverse: 'prerequisite' },
  demonstrates: { label: 'Demonstrates', inverse: 'demonstrated-by' },
  'demonstrated-by': { label: 'Demonstrated by', inverse: 'demonstrates' },
};
const REL_ORDER = ['Combines with', 'Enables', 'Requires', 'Demonstrates', 'Demonstrated by'];

const page = (slug: string, source: string, title: string): PageRef => ({
  slug,
  route: `/${source.replace(/^docs\//, '').replace(/\.md$/, '.html')}`,
  source,
  title,
});
const PAGES = new Map<string, PageRef>(
  [
    page('circuit-breaker', 'docs/patterns/distributed/resilience/circuit-breaker.md', 'Circuit Breaker'),
    page('bulkhead', 'docs/patterns/distributed/resilience/bulkhead.md', 'Bulkhead'),
    page('timeout', 'docs/patterns/distributed/resilience/timeout.md', 'Timeout / Deadline'),
    page('persona', 'docs/designs/persona.md', 'Persona & Sanction *Check*'),
  ].map((p) => [p.slug, p]),
);

const FILE: RelationsFile = {
  version: 1,
  updated: '2026-09-23',
  note: 'n',
  relations: [
    { a: 'circuit-breaker', verb: 'combines-with', b: 'bulkhead', note_a: 'Isolate, then stop.', note_b: 'Pair with a breaker.' },
    { a: 'circuit-breaker', verb: 'prerequisite', b: 'timeout', note_a: 'Bound the call {first}', note_b: '' },
    {
      a: 'persona',
      verb: 'demonstrates',
      b: 'circuit-breaker',
      note_a: 'one breaker per vendor',
      note_b: 'a [shared](./bulkhead.md) breaker',
      group_a: 'Vendor resilience',
    },
  ],
};

describe('reading relations.json', () => {
  it('reads an edge from both ends, the far end through the inverse verb', () => {
    expect(inverseOf('prerequisite', VERBS)).toBe('enables');
    expect(inverseOf('combines-with', VERBS)).toBe('combines-with');
    expect(() => inverseOf('nope', VERBS)).toThrow(/unknown verb/);
    expect(sidesOf('timeout', FILE, VERBS)).toEqual([{ verb: 'enables', to: 'circuit-breaker', note: '' }]);
    expect(sidesOf('circuit-breaker', FILE, VERBS).map((s) => `${s.verb} ${s.to}`)).toEqual([
      'combines-with bulkhead',
      'prerequisite timeout',
      'demonstrated-by persona',
    ]);
  });

  it('labels a side by its custom group, else by its verb', () => {
    const [side] = sidesOf('persona', FILE, VERBS);
    expect(side === undefined ? '' : labelOf(side, VERBS)).toBe('Vendor resilience');
    expect(labelOf({ verb: 'enables', to: 'x', note: '' }, VERBS)).toBe('Enables');
    expect(() => labelOf({ verb: 'nope', to: 'x', note: '' }, VERBS)).toThrow(/unknown verb/);
  });

  it('orders groups by REL_ORDER, custom labels after, unless the page pins its order', () => {
    const labels = (slug: string, file: RelationsFile): string[] => relationGroups(slug, file, VERBS, REL_ORDER).map((g) => g.label);
    expect(labels('circuit-breaker', FILE)).toEqual(['Combines with', 'Requires', 'Demonstrated by']);
    const pinned = { ...FILE, group_order: { 'circuit-breaker': ['Demonstrated by', 'Combines with'] } };
    expect(labels('circuit-breaker', pinned)).toEqual(['Demonstrated by', 'Combines with', 'Requires']);
  });

  it('records a group order only where the default would not give it', () => {
    expect(groupOrderToRecord(['Combines with', 'Requires'], REL_ORDER)).toBeNull();
    expect(groupOrderToRecord(['Requires', 'Combines with'], REL_ORDER)).toEqual(['Requires', 'Combines with']);
    expect(groupOrderToRecord(['Combines with', 'Vendor resilience'], REL_ORDER)).toEqual(['Combines with', 'Vendor resilience']);
  });
});

describe('renderRelations', () => {
  const ctx = { verbs: VERBS, relOrder: REL_ORDER, pages: PAGES };

  it('writes the stamp, then each group as a bold label over a list', () => {
    expect(renderRelations('circuit-breaker', FILE, ctx)).toEqual([
      `<!-- GENERATED by ${GENERATOR} from ${RELATIONS_SRC}. Do not edit this block. -->`,
      '',
      '**Combines with**',
      '',
      '- [Bulkhead](./bulkhead.md) — Isolate, then stop.',
      '',
      '**Requires**',
      '',
      '- [Timeout / Deadline](./timeout.md) — Bound the call \\{first}',
      '',
      '**Demonstrated by**',
      '',
      '- [Persona & Sanction \\*Check\\*](../../../designs/persona.md) — a [shared](./bulkhead.md) breaker',
    ]);
    expect(BLOCK).toBe('relationships');
  });

  it('omits the dash when the side has no note, and escapes a title', () => {
    const lines = renderRelations('timeout', FILE, ctx);
    expect(lines).toContain('- [Circuit Breaker](./circuit-breaker.md)');
  });

  it('parses back to the target titles, with no suffix taken from a note', () => {
    const md = renderRelations('circuit-breaker', FILE, ctx).join('\n');
    const { tree, problems } = parseKb(md);
    expect(problems).toEqual([]);
    const text = plainText(tree);
    expect(text).toContain('Persona & Sanction *Check* — a shared breaker');
    expect(text).toContain('Bound the call {first}');
  });

  it('refuses an edge to a page it does not know', () => {
    const bad: RelationsFile = { ...FILE, relations: [{ a: 'bulkhead', verb: 'combines-with', b: 'ghost', note_a: '', note_b: '' }] };
    expect(() => renderRelations('bulkhead', bad, ctx)).toThrow(/ghost/);
    expect(() => renderRelations('ghost', FILE, ctx)).toThrow(/no page/);
  });
});
