/**
 * Every published page keeps one shape, PAGE-001 to PAGE-008 of
 * docs/reference/page-rules.md (spec: kb.content.page-shape). Findings are in
 * the rule-id shape and carry the rule's anchor; code fences are invisible.
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { PAGE_ALPHA, PAGE_GUIDE, PAGE_THEME, pagesTree, pageText, structureJson } from '../lib/fixtures.js';
import { capture, expectFail, expectMisuse, expectPass, makeSandbox, REPO_ROOT, type Sandbox } from '../lib/sandbox.js';
import { measuredSet, pageFindings, publishedSources, RULES_PAGE, shaped, spec } from './check-docs-style.js';

let sb: Sandbox;
beforeEach(() => {
  sb = makeSandbox();
  pagesTree(sb);
});
afterEach(() => sb.cleanup());

/** The real tree is 380-odd pages: on a loaded machine one run outlasts the suite's default. */
const REAL_TREE_TIMEOUT = 180_000;

/** The finding ids and lines one page body gives, as `ID:line`. */
const ids = (text: string, type: 'md' | 'mdx' = 'md', desc: string | undefined = 'Fine.'): string[] => pageFindings(text, type, desc).map((f) => `${f.id}:${String(f.line)}`);

/** A page body with its H1, intro and one section; lines are numbered from 1. */
const page = (...body: string[]): string => ['---', 'description: Fine.', '---', '', '# Title', '', 'Intro.', '', ...body].join('\n');

it('page-shape-O1: an H4 on line 12 fails PAGE-002 there; four backticks hide a #### sample until it moves out', async () => {
  const deep = 'docs/patterns/caching/deep.md';
  const fenced = 'docs/patterns/caching/fenced.md';
  sb.write('docs/data/site-structure.json', structureJson({ caching: [PAGE_ALPHA, deep, fenced], 'themes-data': [PAGE_THEME], reference: [PAGE_GUIDE] }));
  const lines = pageText({ title: 'Deep' }).split('\n');
  lines.splice(11, 0, '#### Too deep', '');
  sb.write(deep, lines.join('\n'));
  expect(sb.read(deep).split('\n')[11]).toBe('#### Too deep');
  const r1 = await sb.run(spec, [deep]);
  expectFail(r1);
  const err1 = r1.err.split('\n').filter((l) => l !== '');
  expect(err1).toEqual([`PAGE-002 ${deep}:12 heading deeper than H3 — a page that needs H4 is two pages (${RULES_PAGE}#PAGE-002)`]);
  expect(err1.some((l) => l.includes('FAIL'))).toBe(false);

  sb.write(fenced, pageText({ title: 'Fenced' }, ['## Sample', '', '````markdown', '```bash', '#### a sample heading', '```', '````', ''].join('\n')));
  expectPass(await sb.run(spec, [fenced]));

  const moved = sb.read(fenced).replace('#### a sample heading\n```\n````\n', '```\n````\n#### a sample heading\n');
  sb.write(fenced, moved);
  const at = moved.split('\n').indexOf('#### a sample heading') + 1;
  const r3 = await sb.run(spec, [fenced]);
  expectFail(r3);
  expect(r3.err.split('\n').filter((l) => l !== '')).toEqual([`PAGE-002 ${fenced}:${String(at)} heading deeper than H3 — a page that needs H4 is two pages (${RULES_PAGE}#PAGE-002)`]);
});

describe('the measured set', () => {
  it('passes the published pages of a clean tree', async () => {
    const r = await sb.run(spec);
    expectPass(r);
    expect(r.out).toBe(`[docs-style] OK — 3 page(s) keep the shape of ${RULES_PAGE}`);
  });

  it('holds the real tree', async () => {
    const r = await capture(spec, [], REPO_ROOT);
    expectPass(r);
    expect(Number(/(\d+) page/.exec(r.out)?.[1])).toBeGreaterThan(380);
  }, REAL_TREE_TIMEOUT);

  it('measures only what the structure file publishes, plus the unstamped site pages', async () => {
    sb.write('docs/patterns/caching/unlisted.md', '# One\n# Two\n');
    sb.write('site/src/content/docs/start/quickstart.mdx', '---\ntitle: Start\ndescription: Go.\n---\n\nIntro.\n');
    sb.write('site/src/content/docs/caching/index.mdx', '<!-- GENERATED by gen-site-hubs from x. Do not edit this file. -->\n# Hub\n');
    sb.write('site/src/content/docs/notes.txt', 'not a page\n');
    expect(measuredSet(sb.dir)).toEqual([PAGE_ALPHA, 'docs/themes/tour.md', PAGE_GUIDE, 'site/src/content/docs/start/quickstart.mdx']);
    expectPass(await sb.run(spec));
  });

  it('skips a published page gone from disk with a note', async () => {
    sb.rm(PAGE_GUIDE);
    const r = await sb.run(spec);
    expectPass(r);
    expect(r.err).toContain(`skipped ${PAGE_GUIDE}: docs/data/site-structure.json publishes it, and it is not on disk`);
  });

  it('still measures the rows of an unpublished (`nav: none`) area: the gate reads the raw rows', () => {
    sb.write('docs/data/site-structure.json', JSON.stringify({ areas: [{ id: 'reference', nav: 'none', pages: [{ source: PAGE_GUIDE }] }] }));
    expect(publishedSources(sb.dir)).toEqual([PAGE_GUIDE]);
    expect(measuredSet(sb.dir)).toContain(PAGE_GUIDE);
  });

  it('reads only rows the page tree holds', () => {
    sb.write('docs/data/site-structure.json', JSON.stringify({ areas: [{ pages: [{ source: 'site' }, { source: PAGE_GUIDE }, { source: PAGE_GUIDE }] }, {}] }));
    expect(publishedSources(sb.dir)).toEqual([PAGE_GUIDE]);
    sb.write('docs/data/site-structure.json', '{}');
    expect(publishedSources(sb.dir)).toEqual([]);
  });

  it('fails PAGE-000 in the rule-id shape when the structure file is missing or is not JSON, named files or not', async () => {
    const want = `PAGE-000 docs/data/site-structure.json:1 is missing or is not JSON — the measured set is the pages it publishes (${RULES_PAGE}#PAGE-000)`;
    sb.rm('docs/data/site-structure.json');
    for (const argv of [[], [PAGE_GUIDE]]) {
      const r = await sb.run(spec, argv);
      expectFail(r);
      expect(r.err.trim()).toBe(want);
      expect(r.err).not.toContain('FAIL');
    }
    sb.write('docs/data/site-structure.json', 'not json');
    expect(publishedSources(sb.dir)).toBeNull();
    expect(measuredSet(sb.dir)).toBeNull();
    expect((await sb.run(spec)).err.trim()).toBe(want);
  });

  it('knows a shaped page', () => {
    expect(shaped('docs/reference/page-rules.md')).toBe(true);
    expect(shaped('docs/CLAUDE.md')).toBe(false);
    expect(shaped('docs/records/2026-09-24-x.md')).toBe(false);
    expect(shaped('docs/exercises/a.md')).toBe(false);
    expect(shaped('site/src/content/docs/a.mdx')).toBe(true);
    expect(shaped('site/src/content/docs/a.md')).toBe(false);
    expect(shaped('README.md')).toBe(false);
  });
});

describe('arguments', () => {
  it('narrows to named pages and skips one it does not measure', async () => {
    sb.write('docs/records/2026-09-24-x.md', '# One\n# Two\n');
    const r = await sb.run(spec, [PAGE_GUIDE, 'docs/records/2026-09-24-x.md', 'docs/CLAUDE.md']);
    expectPass(r);
    expect(r.out).toContain('1 page(s)');
  });

  it('never widens the set: a named working file, unlisted page or stamped hub is skipped, as the whole run skips it', async () => {
    // What `make validate-changed` hands over after an edit to the trap inbox or the map's rows.
    const inbox = 'docs/inbox.md';
    const unlisted = 'docs/patterns/caching/unlisted.md';
    const hub = 'site/src/content/docs/caching/index.mdx';
    sb.write(inbox, pageText({ title: 'Inbox', area: 'reference', description: 'x'.repeat(200) }, '## Loose\n\n#### Too deep\n'));
    sb.write(unlisted, '# One\n# Two\n');
    sb.write(hub, '{/* GENERATED by gen-site-hubs from x. Do not edit this file. */}\n---\ntitle: Hub\ndescription: All of it.\n---\n\n## No intro\n');
    expectPass(await sb.run(spec));
    const named = await sb.run(spec, [inbox, unlisted, hub]);
    expectPass(named);
    expect(named.out).toContain('0 page(s)');
  });

  it('measures the whole set when the structure file is named, since it decides the set', async () => {
    sb.write(PAGE_GUIDE, pageText({ title: 'Guide', area: 'reference' }, '#### Too deep\n'));
    const r = await sb.run(spec, [PAGE_ALPHA, './docs/data/site-structure.json']);
    expectFail(r, `PAGE-002 ${PAGE_GUIDE}:`);
    sb.write(PAGE_GUIDE, pageText({ title: 'Guide', area: 'reference' }));
    const clean = await sb.run(spec, ['docs/data/site-structure.json']);
    expectPass(clean);
    expect(clean.out).toContain('3 page(s)');
  });

  it('is misuse for an unknown flag, --fix or a missing named file, with nothing on stdout', async () => {
    for (const argv of [['--nope'], ['--fix'], ['docs/nope.md']]) {
      const r = await sb.run(spec, argv);
      expectMisuse(r);
      expect(r.out).toBe('');
    }
  });
});

describe('PAGE-001 · the intro', () => {
  it('fails a page whose first H2 comes before any prose', () => {
    expect(ids('---\ndescription: x\n---\n\n# T\n\n- a list\n\n## A\n\nText.')).toEqual(['PAGE-001:4']);
  });

  it('reads markup, a table, an image, a quote, an aside, an import and indented code as no prose', () => {
    const body = ['<!-- stamp -->', '| a |', '![x](y.png)', '> quote', '{#an-id}', ':::note', 'import X from "y"', '    code', '1. item'];
    expect(ids(['# T', '', ...body, '', '## A', ''].join('\n'))).toContain('PAGE-001:1');
  });
});

describe('PAGE-002 · no H4', () => {
  it('fails an H4 with up to three leading spaces, and no four-space-indented line', () => {
    expect(ids(page('   #### x', '', '    #### code', ''))).toEqual(['PAGE-002:9']);
  });

  it('fails an H4, H5 or H6 only when a space or the line end follows the hashes', () => {
    expect(ids(page('####word is a paragraph', '', '####### seven is a paragraph', '', '#####', '', '###### Six', ''))).toEqual(['PAGE-002:13', 'PAGE-002:15']);
  });

  it('reads a four-space-indented backtick run outside a list as code, which hides nothing after it', () => {
    expect(ids(page('    ```', '', '#### real h4', ''))).toEqual(['PAGE-002:11']);
  });

  it('never reads inside a tilde fence', () => {
    expect(ids(page('~~~', '#### x', '# y', '~~~', ''))).toEqual([]);
  });
});

describe('PAGE-003 and PAGE-008 · Next steps', () => {
  const footer = (...lines: string[]): string => page('## About', '', 'Text.', '', '## Next steps', '', ...lines);

  it('passes one sentence and one link, a wrapped item counting once', () => {
    expect(ids(footer('Read on:', '', '- [Next](next.md) — why,', '  and more.', ''))).toEqual([]);
  });

  it('fails a footer with no link, or two, and does not count a link in the lead sentence', () => {
    expect(ids(footer('Read [the lead](x.md):', '', '- nothing linked', ''))).toEqual(['PAGE-003:13']);
    expect(ids(footer('Read on:', '', '- [A](a.md)', '- [B](b.md)', ''))).toEqual(['PAGE-003:13']);
  });

  it('fails a section after the footer', () => {
    expect(ids(footer('Read on:', '', '- [A](a.md)', '', '## After', '', 'Text.', ''))).toEqual(['PAGE-003:19']);
  });

  it('fails a footer that opens with its list, or trails prose after it', () => {
    expect(ids(footer('- [A](a.md)', ''))).toEqual(['PAGE-008:13']);
    expect(ids(footer('Read on:', '', '- [A](a.md)', '', 'And then.', ''))).toEqual(['PAGE-008:19']);
    expect(ids(footer('Read on:', '- [A](a.md)', 'And then.', ''))).toEqual(['PAGE-008:17']);
  });

  it('fails a footer that opens with two paragraphs, on the second, and passes one sentence wrapped over two lines', () => {
    const two = pageFindings(footer('Read next.', '', 'Another paragraph here.', '', '- [A](a.md)', ''), 'md', 'Fine.');
    expect(two.map((f) => `${f.id}:${String(f.line)} ${f.message}`)).toEqual(['PAGE-008:17 the "Next steps" section opens with 2 paragraphs — one sentence saying where this leads, then the list']);
    expect(ids(footer('Read next, which picks up', 'where this page stops.', '', '- [A](a.md)', ''))).toEqual([]);
  });

  it('lets a page end without a footer', () => {
    expect(ids(page('## About', '', 'Text.', ''))).toEqual([]);
  });
});

describe('PAGE-004 · one H1', () => {
  it('fails zero or two H1 lines, at the block end or the second one', () => {
    expect(ids('---\ndescription: x\n---\nIntro.\n')).toEqual(['PAGE-004:4']);
    expect(ids(page('# Again', '', '# Third', ''))).toEqual(['PAGE-004:9']);
  });

  it('fails any H1 in a hand-written site page, which takes its H1 from title:', () => {
    expect(ids('---\ndescription: x\n---\nIntro.\n', 'mdx')).toEqual([]);
    expect(ids(page(), 'mdx')).toEqual(['PAGE-004:5']);
  });
});

describe('PAGE-005 · the description', () => {
  const at = (desc: string | undefined, text = page()): string[] => pageFindings(text, 'md', desc).map((f) => `${f.id}:${String(f.line)} ${f.message}`);

  it('passes 160 characters, an em dash counting once, and quotes not counting', () => {
    expect(at('—'.repeat(160))).toEqual([]);
    expect(at(`"${'a'.repeat(160)}"`)).toEqual([]);
    expect(at(`'${'a'.repeat(160)}'`)).toEqual([]);
  });

  it('fails 161 characters on the key line', () => {
    expect(at('a'.repeat(161))).toEqual(['PAGE-005:2 description is 161 characters — 160 is where search results cut off']);
  });

  it('fails a block scalar and a missing description', () => {
    expect(at('>')).toEqual(['PAGE-005:2 description is a block scalar — write it as one plain line so its length means something']);
    expect(at(undefined, '# T\n\nIntro.\n')).toEqual(['PAGE-005:1 no description: in the frontmatter']);
  });
});

describe('PAGE-006 · no raw URL in prose', () => {
  it('fails a bare address in prose', () => {
    expect(ids(page('See https://example.com for more.', ''))).toEqual(['PAGE-006:9']);
  });

  it('exempts inline code, a link target, indented code and a reference definition', () => {
    expect(ids(page('Run `curl https://x.test` or [read](https://x.test).', '', '    https://x.test', '', '[ref]: https://x.test', ''))).toEqual([]);
  });

  it('exempts a code span of any backtick run, one that wraps a line, and an HTML comment', () => {
    expect(ids(page('See ``https://example.com`` here, and ``a ` https://x.test``.', '', 'Run `curl', 'https://x.test` now.', '', '<!-- https://x.test -->', ''))).toEqual([]);
    expect(ids(page('An ``unclosed https://x.test', ''))).toEqual(['PAGE-006:9']);
  });
});

describe('the finding line', () => {
  it('carries the rule id first and the anchor last', async () => {
    sb.write(PAGE_GUIDE, pageText({ title: 'Guide', area: 'reference', description: 'x'.repeat(170) }));
    const r = await sb.run(spec);
    expectFail(r);
    expect(r.err.trim()).toBe(`PAGE-005 ${PAGE_GUIDE}:3 description is 170 characters — 160 is where search results cut off (${RULES_PAGE}#PAGE-005)`);
  });
});
