/**
 * The structure gate: a bad edit to the one publishing decision fails without
 * a build, every fault in one run (spec: kb.data.structure).
 */

import fs from 'node:fs';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { CONTENT, STRUCTURE, TYPES_FILE } from '../lib/published.js';
import { capture, expectFail, expectMisuse, expectPass, makeSandbox, REPO_ROOT, type Sandbox } from '../lib/sandbox.js';
import { handWrittenInputPages, inputPagesForRoute, NAME, ROUTE, spec } from './check-site-structure.js';

type Json = Record<string, unknown>;

const hub = (): Json => ({ description: 'What the area holds.', intro: 'Start here.', tags: ['caching', 'latency'] });

/** A coherent tree: two areas nested under a third, one site page, one generated area. */
function tree(): { areas: Json[] } {
  return {
    areas: [
      { id: 'patterns', label: 'Patterns', hub: hub(), pages: [] },
      {
        id: 'caching',
        label: 'Caching',
        nestUnder: 'patterns',
        hub: hub(),
        pages: [
          { slug: 'cache-aside', label: 'Cache-Aside', source: 'docs/patterns/caching/cache-aside.md', route: '/patterns/caching/cache-aside.html' },
          { slug: 'read-through', label: 'Read-Through', source: 'docs/patterns/caching/read-through.md', route: '/patterns/caching/read-through.html' },
        ],
      },
      { id: 'start', label: 'Start', hub: hub(), pages: [{ slug: 'tour', label: 'Tour', source: 'site' }] },
      { id: 'map', label: 'Map', generated: 'tools/src/gen/gen-map.ts', hub: hub(), pages: [{ slug: 'stack', label: 'Stack', source: 'generated' }] },
    ],
  };
}

const typesFile = (areas: readonly string[]): string => `export const AREAS = [\n${areas.map((a) => `  '${a}',`).join('\n')}\n] as const;\n`;
const IDS = ['patterns', 'caching', 'start', 'map'];

function writeStructure(data: unknown): void {
  sb.write(STRUCTURE, `${JSON.stringify({ version: 1, updated: '2026-09-24', note: 'n', ...(data as Json) }, null, 2)}\n`);
}

let sb: Sandbox;
beforeEach(() => {
  sb = makeSandbox();
  writeStructure(tree());
  sb.write(TYPES_FILE, typesFile(IDS));
  sb.write('docs/patterns/caching/cache-aside.md', '# Cache-Aside\n');
  sb.write('docs/patterns/caching/read-through.md', '# Read-Through\n');
  sb.write(`${CONTENT}/start/tour.mdx`, '---\ntitle: Tour\n---\n');
  sb.write(`${CONTENT}/index.mdx`, '---\ntitle: Home\n---\n');
  track(`${CONTENT}/start/tour.mdx`, `${CONTENT}/index.mdx`);
});
afterEach(() => sb.cleanup());

/** Stage input pages: the gate counts what git tracks there, never an untracked draft. */
function track(...files: string[]): void {
  sb.git('add', '--', ...files);
}

const areas = (): Json[] => (JSON.parse(sb.read(STRUCTURE)) as { areas: Json[] }).areas;
const edit = (fn: (a: Json[]) => void): void => {
  const a = areas();
  fn(a);
  writeStructure({ areas: a });
};
const area = (a: Json[], id: string): Json => a.find((x) => x['id'] === id) as Json;
const pages = (a: Json[], id: string): Json[] => area(a, id)['pages'] as Json[];

describe('a coherent tree', () => {
  it('exits 0 with one summary line counting areas and routes', async () => {
    const r = await sb.run(spec);
    expectPass(r);
    // Four area routes and four rows.
    expect(r.out).toBe(`[${NAME}] ${STRUCTURE} is coherent (4 areas, 8 routes)`);
    expect(r.err).toBe('');
  });

  it('runs with no input folder and no site build installed', async () => {
    edit((a) => {
      pages(a, 'start').length = 0;
    });
    sb.rm('site/src/content');
    expectPass(await sb.run(spec));
  });

  it('needs no file on disk for a generated row in an area declaring its generator', async () => {
    expect(sb.exists(`${CONTENT}/map/stack.mdx`)).toBe(false);
    expectPass(await sb.run(spec));
  });

  it('accepts a site page written as .md', async () => {
    sb.rm(`${CONTENT}/start/tour.mdx`);
    sb.write(`${CONTENT}/start/tour.md`, '---\ntitle: Tour\n---\n');
    track(`${CONTENT}/start/tour.md`);
    expectPass(await sb.run(spec));
  });

  it('treats a stamped page in the input folder as output, never as an unlisted page, in either comment form', async () => {
    const stamp = 'GENERATED by tools/src/gen/gen-site-docs.ts from docs/patterns/caching/cache-aside.md. Do not edit this file.';
    sb.write(`${CONTENT}/patterns/caching/cache-aside.md`, `---\ntitle: Cache-Aside\n---\n\n<!-- ${stamp} -->\n`);
    sb.write(`${CONTENT}/caching/index.mdx`, `---\ntitle: Caching\n---\n\n{/* ${stamp} */}\n`);
    track(`${CONTENT}/patterns/caching/cache-aside.md`, `${CONTENT}/caching/index.mdx`);
    expectPass(await sb.run(spec));
  });

  it('takes no arguments', async () => {
    expectMisuse(await sb.run(spec, ['docs/data/site-structure.json']));
    expectMisuse(await sb.run(spec, ['--fix']));
  });
});

describe('structure-O3', () => {
  it('reports each planted fault in one run, the unknown area against the closed area list, and builds nothing', async () => {
    expectPass(await sb.run(spec));
    edit((a) => {
      // An unknown area: declared here, absent from the closed area list.
      a.push({ id: 'extras', label: 'Extras', hub: hub(), pages: [{ slug: 'odd', label: 'Odd', source: 'docs/patterns/caching/read-through.md', route: '/extras/odd/' }] });
      // A row with no source.
      pages(a, 'caching').push({ slug: 'sourceless', label: 'Sourceless' });
      // A generated row in an area that declares no generator.
      pages(a, 'start').push({ slug: 'made', label: 'Made', source: 'generated' });
      // Two rows sharing a route.
      pages(a, 'caching').push({ slug: 'twin', label: 'Twin', source: 'docs/patterns/caching/read-through.md', route: '/patterns/caching/cache-aside.html' });
      // An area with a bad id.
      a.push({ id: 'Bad_Area', label: 'Bad', hub: hub(), pages: [] });
    });
    sb.write(TYPES_FILE, typesFile([...IDS, 'Bad_Area']));
    // An unlisted committed input page.
    sb.write(`${CONTENT}/start/secret.mdx`, '---\ntitle: Secret\n---\n');
    sb.commit('the planted tree');
    const before = sb.snapshot();

    const r = await sb.run(spec);
    expectFail(r);
    expect(r.out).toBe('');
    const lines = r.err.split('\n').filter((l) => l !== '');
    const one = (needle: string): void => {
      expect(lines.filter((l) => l.includes(needle)), needle).not.toHaveLength(0);
    };
    one(`[${NAME}] FAIL ${STRUCTURE}: area 'extras' is not in the closed area list (AREAS in ${TYPES_FILE})`);
    one(`[${NAME}] FAIL ${STRUCTURE}: area 'caching' page 'sourceless': no source`);
    one(`[${NAME}] FAIL ${STRUCTURE}: area 'start' page 'made': source 'generated' but area 'start' declares no generator`);
    one(`[${NAME}] FAIL ${STRUCTURE}: area 'caching' page 'twin': route /patterns/caching/cache-aside.html is already taken`);
    one(`[${NAME}] FAIL ${CONTENT}/start/secret.mdx: not listed in ${STRUCTURE}`);
    one(`[${NAME}] FAIL ${STRUCTURE}: area id 'Bad_Area' is not kebab-case`);
    // Every finding line is one of the planted faults: nothing else broke.
    expect(lines.every((l) => l.startsWith(`[${NAME}] FAIL `))).toBe(true);
    expect(lines).toHaveLength(6);
    // No build ran and nothing was written.
    expect(sb.snapshot()).toEqual(before);
    expect(sb.exists('site/dist')).toBe(false);
  });
});

describe('areas', () => {
  it('fails an unreadable file once, and runs no other check', async () => {
    sb.write(STRUCTURE, '{ nope');
    sb.rm(TYPES_FILE);
    const r = await sb.run(spec);
    expectFail(r, `[${NAME}] FAIL ${STRUCTURE}: unreadable:`);
    expect(r.err.split('\n').filter((l) => l.includes('FAIL'))).toHaveLength(1);

    sb.write(STRUCTURE, '{"sections": []}');
    expectFail(await sb.run(spec), `${STRUCTURE}: unreadable: has no \`areas\` list`);
  });

  it('fails a duplicate id, a missing label, and a hub missing its identity', async () => {
    edit((a) => {
      a.push({ id: 'map', label: '', hub: { description: ' ', intro: 'i' }, pages: [] });
      area(a, 'patterns')['hub'] = 'none';
      a.push({ id: 'x', label: 'X', pages: [] });
    });
    const r = await sb.run(spec);
    expectFail(r, `area id 'map' is declared twice`);
    expectFail(r, `area 'map' has no label`);
    expectFail(r, `area 'map' hub has no description`);
    expectFail(r, `area 'patterns' has no hub (description, intro, tags)`);
    expectFail(r, `area 'x' has no hub`);
  });

  it('fails an area label and a row label holding an em-dash, and passes a plain one', async () => {
    expectPass(await sb.run(spec));
    edit((a) => {
      area(a, 'caching')['label'] = 'Caching \u2014 keep it near';
      pages(a, 'caching')[0]!['label'] = 'Cache Aside \u2014 lazy';
    });
    const r = await sb.run(spec);
    expectFail(r, `area 'caching' label "Caching \u2014 keep it near" holds an em-dash`);
    expectFail(r, `label "Cache Aside \u2014 lazy" holds an em-dash`);
    expectFail(r, 'its tagline goes in hub.description');
  });

  it('fails an empty generator and an area with no pages list', async () => {
    edit((a) => {
      area(a, 'map')['generated'] = '';
      delete area(a, 'patterns')['pages'];
    });
    const r = await sb.run(spec);
    expectFail(r, `area 'map' declares an empty generator`);
    expectFail(r, `area 'patterns' has no pages list`);
  });

  it('passes a link area with one row and a none area, and fails a nav outside link and none', async () => {
    edit((a) => {
      area(a, 'map')['nav'] = 'link';
      area(a, 'start')['nav'] = 'none';
    });
    expectPass(await sb.run(spec));
    edit((a) => {
      area(a, 'map')['nav'] = 'hidden';
    });
    expectFail(await sb.run(spec), `area 'map' nav "hidden" is not one of link, none`);
  });

  it('fails a link area with two rows, one that nests under another area, and one another area nests under', async () => {
    edit((a) => {
      area(a, 'map')['nav'] = 'link';
      pages(a, 'map').push({ slug: 'more', label: 'More', source: 'generated' });
      area(a, 'caching')['nav'] = 'link';
      pages(a, 'caching').pop();
      a.push({ id: 'under-link', label: 'Under', nestUnder: 'caching', hub: hub(), pages: [] });
    });
    sb.write(TYPES_FILE, typesFile([...IDS, 'under-link']));
    const r = await sb.run(spec);
    expectFail(r, `area 'map' is nav 'link' but holds 2 rows`);
    expectFail(r, `area 'caching' is nav 'link' but nests under 'patterns'`);
    expectFail(r, `area 'under-link' nests under 'caching', a nav 'link' area`);
  });

  it('fails a published area nested under an unpublished one, and passes a none one', async () => {
    edit((a) => {
      area(a, 'patterns')['nav'] = 'none';
    });
    expectFail(await sb.run(spec), `area 'caching' nests under 'patterns', which is unpublished (nav 'none')`);
    edit((a) => {
      area(a, 'caching')['nav'] = 'none';
    });
    expectPass(await sb.run(spec));
  });

  it('fails a nestUnder naming no other declared area', async () => {
    edit((a) => {
      area(a, 'caching')['nestUnder'] = 'ghost';
      area(a, 'start')['nestUnder'] = 'start';
    });
    const r = await sb.run(spec);
    expectFail(r, `area 'caching' nests under 'ghost', which is no other declared area`);
    expectFail(r, `area 'start' nests under 'start', which is no other declared area`);
  });

  it('fails an area whose id is not a string', async () => {
    edit((a) => {
      a.push({ id: 7, label: 'Seven', hub: hub(), pages: [] });
    });
    expectFail(await sb.run(spec), `area id '' is not kebab-case`);
  });

  it('fails an area and a row that are not objects, one finding each, and checks the rest', async () => {
    edit((a) => {
      pages(a, 'caching').splice(1, 0, null as unknown as Json);
      pages(a, 'start').push(3 as unknown as Json, { slug: 'late', source: 'docs/patterns/caching/read-through.md' });
      a.splice(1, 0, null as unknown as Json);
      a.push('extras' as unknown as Json);
    });
    const r = await sb.run(spec);
    expectFail(r);
    const lines = r.err.split('\n').filter((l) => l !== '');
    expect(lines.every((l) => l.startsWith(`[${NAME}] FAIL `)), r.err).toBe(true);
    expect(lines).toEqual([
      `[${NAME}] FAIL ${STRUCTURE}: area #2 is not an object`,
      `[${NAME}] FAIL ${STRUCTURE}: area #6 is not an object`,
      `[${NAME}] FAIL ${STRUCTURE}: area 'caching' row #2 is not an object`,
      `[${NAME}] FAIL ${STRUCTURE}: area 'start' row #2 is not an object`,
      // The checks after the bad entries still run.
      `[${NAME}] FAIL ${STRUCTURE}: area 'start' page 'late': no label`,
    ]);
  });
});

describe('rows', () => {
  it('fails a bad slug, a missing label and a route that is no path', async () => {
    edit((a) => {
      pages(a, 'caching').push({ slug: 'Two Words', label: 'X', source: 'docs/patterns/caching/read-through.md', route: '/two/words/' });
      pages(a, 'caching').push({ slug: 'unlabelled', source: 'docs/patterns/caching/read-through.md', route: '/u/' });
      pages(a, 'caching').push({ slug: 'relative', label: 'R', source: 'docs/patterns/caching/read-through.md', route: 'patterns/r.html' });
      pages(a, 'caching').push({ slug: 'bad-slug', label: 'B' });
      (pages(a, 'caching')[5] as Json)['slug'] = 5;
    });
    const r = await sb.run(spec);
    expectFail(r, `area 'caching' page 'Two Words': slug is not kebab-case`);
    expectFail(r, `area 'caching' page 'unlabelled': no label`);
    expectFail(r, `area 'caching' page 'relative': route "patterns/r.html" is not a path from / ending in / or .html`);
    expectFail(r, `area 'caching' page '': slug is not kebab-case`);
  });

  it('fails a route an area already takes, and one the home page takes, naming whichever comes later', async () => {
    edit((a) => {
      pages(a, 'caching').push({ slug: 'clash', label: 'C', source: 'docs/patterns/caching/read-through.md', route: '/map/' });
      pages(a, 'caching').push({ slug: 'home', label: 'H', source: 'docs/patterns/caching/read-through.md', route: '/' });
    });
    const r = await sb.run(spec);
    // The row claims /map/ first; the map area, read later, is the one refused.
    expectFail(r, `area 'map': route /map/ is already taken`);
    expectFail(r, `area 'caching' page 'home': route / is already taken`);
  });

  it('fails two published pages in different areas that share a file name, since marks are stored by it', async () => {
    edit((a) => {
      pages(a, 'start').push({ slug: 'clash', label: 'C', source: 'docs/patterns/caching/read-through.md', route: '/start/shared.html' });
      pages(a, 'caching').push({ slug: 'other', label: 'O', source: 'docs/patterns/caching/read-through.md', route: '/patterns/caching/shared.html' });
    });
    expectFail(await sb.run(spec), `area 'start' page 'clash': file name 'shared' is also a page in area 'caching'`);
  });

  it('lets an unpublished area reuse a published page\'s file name', async () => {
    edit((a) => {
      pages(a, 'start').push({ slug: 'clash', label: 'C', source: 'docs/patterns/caching/read-through.md', route: '/start/shared.html' });
      a.push({ id: 'hidden', label: 'Hidden', nav: 'none', hub: hub(), pages: [{ slug: 'shared', label: 'S', source: 'docs/patterns/caching/read-through.md', route: '/hidden/shared.html' }] });
    });
    sb.write(TYPES_FILE, typesFile([...IDS, 'hidden']));
    expectPass(await sb.run(spec));
  });

  it('fails a site row with no committed page at its route', async () => {
    sb.rm(`${CONTENT}/start/tour.mdx`);
    expectFail(await sb.run(spec), `area 'start' page 'tour': source 'site' but no committed page at ${CONTENT}/start/tour.md or ${CONTENT}/start/tour.mdx`);
  });

  it('fails a source outside the page tree, and one that does not exist', async () => {
    edit((a) => {
      (pages(a, 'caching')[0] as Json)['source'] = 'site/index.html';
      (pages(a, 'caching')[1] as Json)['source'] = 'docs/patterns/caching/gone.md';
    });
    const r = await sb.run(spec);
    expectFail(r, `area 'caching' page 'cache-aside': source site/index.html is not a page under docs/`);
    expectFail(r, `area 'caching' page 'read-through': source docs/patterns/caching/gone.md does not exist`);
  });
});

describe('the closed area list', () => {
  it('fails a missing types file, and a reshaped declaration rather than comparing against nothing', async () => {
    sb.rm(TYPES_FILE);
    expectFail(await sb.run(spec), `${TYPES_FILE}: missing — AREAS here is the closed area list`);
    sb.write(TYPES_FILE, 'export const AREAS = new Set();\n');
    expectFail(await sb.run(spec), 'no `const AREAS = [...]`');
  });

  it('names the list holding a member no area declares', async () => {
    sb.write(TYPES_FILE, typesFile([...IDS, 'retired']));
    expectFail(await sb.run(spec), `[${NAME}] FAIL ${TYPES_FILE}: AREAS lists 'retired', which no area in ${STRUCTURE} declares`);
  });

  it('does not count an area commented out of AREAS', async () => {
    sb.write(TYPES_FILE, typesFile(IDS).replace(`  'caching',`, `  // 'caching',`));
    const r = await sb.run(spec);
    expectFail(r);
    expect(r.err.split('\n').filter((l) => l !== '')).toEqual([
      `[${NAME}] FAIL ${STRUCTURE}: area 'caching' is not in the closed area list (AREAS in ${TYPES_FILE}) — add it there too, or every page in it fails the site's schema`,
    ]);
  });

  it('reads a comment holding an apostrophe as a comment, with no finding', async () => {
    sb.write(TYPES_FILE, typesFile(IDS).replace(`  'caching',`, `  // the band's leaf areas\n  'caching',`));
    expectPass(await sb.run(spec));
  });

  it('fails an area listed twice in AREAS, even at the end where the order check does not reach', async () => {
    sb.write(TYPES_FILE, typesFile([...IDS, 'map']));
    const r = await sb.run(spec);
    expectFail(r);
    expect(r.err.split('\n').filter((l) => l !== '')).toEqual([
      `[${NAME}] FAIL ${TYPES_FILE}: AREAS lists 'map' more than once — the two lists hold one sequence, each area in it once`,
    ]);
  });

  it('fails a sequence of another length when the structure file declares an area twice', async () => {
    edit((a) => {
      a.push({ id: 'map', label: 'Map again', hub: hub(), pages: [] });
    });
    const r = await sb.run(spec);
    expectFail(r, `area id 'map' is declared twice`);
    expectFail(r, `[${NAME}] FAIL ${TYPES_FILE}: AREAS holds 4 areas and ${STRUCTURE} 5 — the two lists hold one sequence`);
  });

  it('holds one sequence: swapping two areas in one list alone fails, in both it passes', async () => {
    sb.write(TYPES_FILE, typesFile(['patterns', 'start', 'caching', 'map']));
    expectFail(await sb.run(spec), `AREAS runs in another order than ${STRUCTURE}: position 2 is 'start' there and 'caching' here`);
    edit((a) => {
      const i = a.findIndex((x) => x['id'] === 'caching');
      const [c] = a.splice(i, 1);
      a.splice(2, 0, c as Json);
    });
    expectPass(await sb.run(spec));
  });
});

describe('the input folder', () => {
  it('leaves the not-found page out of the listing rule, as it does the home page', async () => {
    sb.write(`${CONTENT}/404.mdx`, '---\ntitle: Not found\n---\n');
    track(`${CONTENT}/404.mdx`);
    expectPass(await sb.run(spec));
  });

  it('skips the home page, and lists a hand-written page only by a site row', async () => {
    sb.write(`${CONTENT}/extra.md`, '# Extra\n');
    track(`${CONTENT}/extra.md`);
    expect(handWrittenInputPages(sb.dir)).toEqual([`${CONTENT}/extra.md`, `${CONTENT}/start/tour.mdx`]);
    expectFail(await sb.run(spec), `${CONTENT}/extra.md: not listed in ${STRUCTURE}`);
  });

  it('reports a hand-written page that only mentions a stamp, in prose or in code', async () => {
    sb.write(`${CONTENT}/start/about.mdx`, '---\ntitle: About\n---\n\nThe hub is GENERATED by a script; this page is not.\n');
    const quoted = '<!-- GENERATED by tools/src/gen/x.ts from docs/data/x.json. Do not edit this file. -->';
    sb.write(`${CONTENT}/start/stamps.md`, `---\ntitle: Stamps\n---\n\nA generated page opens with \`${quoted}\`.\n\n\`\`\`markdown\n${quoted}\n\`\`\`\n`);
    track(`${CONTENT}/start/about.mdx`, `${CONTENT}/start/stamps.md`);
    const r = await sb.run(spec);
    expectFail(r);
    expect(r.err.split('\n').filter((l) => l !== '')).toEqual([
      `[${NAME}] FAIL ${CONTENT}/start/about.mdx: not listed in ${STRUCTURE} — give it a 'site' row, or move it out of ${CONTENT}`,
      `[${NAME}] FAIL ${CONTENT}/start/stamps.md: not listed in ${STRUCTURE} — give it a 'site' row, or move it out of ${CONTENT}`,
    ]);
  });

  it('counts only what git tracks: an untracked draft is no finding, and cannot back a site row', async () => {
    sb.write(`${CONTENT}/start/draft.mdx`, '---\ntitle: Draft\n---\n');
    expectPass(await sb.run(spec));
    edit((a) => {
      pages(a, 'start').push({ slug: 'draft', label: 'Draft', source: 'site' });
    });
    expectFail(await sb.run(spec), `area 'start' page 'draft': source 'site' but no committed page at ${CONTENT}/start/draft.md or ${CONTENT}/start/draft.mdx`);
    track(`${CONTENT}/start/draft.mdx`);
    expectPass(await sb.run(spec));
  });

  it('does not count a tracked page deleted from disk', async () => {
    sb.write(`${CONTENT}/extra.md`, '# Extra\n');
    track(`${CONTENT}/extra.md`);
    sb.rm(`${CONTENT}/extra.md`);
    expectPass(await sb.run(spec));
  });

  it('maps a route to the page it names, either route shape', () => {
    expect(inputPagesForRoute('/start/tour/')).toEqual([`${CONTENT}/start/tour.md`, `${CONTENT}/start/tour.mdx`]);
    expect(inputPagesForRoute('/start/tour.html')).toEqual([`${CONTENT}/start/tour.md`, `${CONTENT}/start/tour.mdx`]);
  });
});

describe('the route shape', () => {
  it('takes a path from / that ends in / or in a .html page', () => {
    for (const ok of ['/', '/a/', '/a/b/', '/a/b.html', '/a/b-c/d_e.html']) expect(ROUTE.test(ok), ok).toBe(true);
    for (const bad of ['', 'a/', '/a', '/a/b', '/A/', '/a//b/']) expect(ROUTE.test(bad), bad).toBe(false);
  });
});

describe('the real tree', () => {
  it('is coherent, counting the areas and routes the structure file declares', async () => {
    // testing-C4: recounted here from the file, not from the gate's reader.
    const data = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, STRUCTURE), 'utf8')) as { areas: { pages: unknown[] }[] };
    const rows = data.areas.reduce((n, a) => n + a.pages.length, 0);
    const r = await capture(spec, [], REPO_ROOT);
    expectPass(r);
    expect(r.out).toBe(`[${NAME}] ${STRUCTURE} is coherent (${String(data.areas.length)} areas, ${String(data.areas.length + rows)} routes)`);
  }, 60_000);
});
